import { FormulaDefinition, MetricDefinition } from "../types";

export const formulaRegistry: FormulaDefinition[] = [
  {
    key: "raw_passthrough",
    name: "원천값 직접 사용",
    description: "하나의 L0 파라미터를 그대로 L1 값으로 사용합니다.",
    equation: "L1 = L0",
    requiredData: [],
    outputType: "number",
  },
  {
    key: "custom_expression",
    name: "사용자 정의 수식",
    description: "L0 파라미터를 조합해 직접 수학식으로 계산합니다.",
    equation: "L1 = f(L0, L0, ...)",
    requiredData: [],
    outputType: "number",
  },
  {
    key: "drawdown_pct",
    name: "최근 고점 대비 하락률",
    description: "현재 가격이 최근 고점 기준선에서 얼마나 내려와 있는지 계산합니다.",
    equation: "((현재가 / 최근 고점) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "near_support_bool",
    name: "지지 구간 근접 여부",
    description: "가격이 지지 구간 근처에서 버티며 안정을 찾는지 확인합니다.",
    equation: "현재가가 최근 지지 저점 대비 0~5% 범위인지 확인",
    requiredData: ["priceHistorySeries"],
    outputType: "boolean",
  },
  {
    key: "valuation_discount_bool",
    name: "밸류에이션 할인 여부",
    description: "현재 밸류에이션이 최근 자기 기준보다 더 싸 보이는지 확인합니다.",
    requiredData: ["valuationSnapshot"],
    outputType: "boolean",
  },
  {
    key: "earnings_soon_bool",
    name: "실적 발표 임박 여부",
    description: "가까운 실적 이벤트가 단기 불확실성을 키우는지 확인합니다.",
    requiredData: ["eventCalendar"],
    outputType: "boolean",
  },
  {
    key: "relative_strength_vs_spy_pct",
    name: "SPY 대비 상대강도",
    description: "일정 구간에서 종목이 시장 기준 대비 얼마나 강하거나 약한지 계산합니다.",
    equation: "종목 60일 수익률 - SPY 60일 수익률",
    requiredData: ["priceHistorySeries", "benchmarkHistorySeries"],
    outputType: "number",
  },
  {
    key: "distance_from_ma_50_pct",
    name: "50일 이동평균선 대비 거리",
    description: "현재 가격이 50일 이동평균선 기준에서 얼마나 떨어져 있는지 계산합니다.",
    equation: "((현재가 / 50일 평균가) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "distance_from_ma_20_pct",
    name: "20일 이동평균선 대비 거리",
    description: "현재 가격이 20일 이동평균선 기준에서 얼마나 떨어져 있는지 계산합니다.",
    equation: "((현재가 / 20일 평균가) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "distance_from_ma_200_pct",
    name: "200일 이동평균선 대비 거리",
    description: "현재 가격이 200일 이동평균선 기준에서 얼마나 떨어져 있는지 계산합니다.",
    equation: "((현재가 / 200일 평균가) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "price_return_20d_pct",
    name: "20일 수익률",
    description: "최근 20거래일 기준 가격 수익률을 계산합니다.",
    equation: "((현재가 / 20일 전 가격) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "price_return_60d_pct",
    name: "60일 수익률",
    description: "최근 60거래일 기준 가격 수익률을 계산합니다.",
    equation: "((현재가 / 60일 전 가격) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "rebound_from_recent_low_pct",
    name: "최근 저점 대비 반등률",
    description: "최근 저점에서 현재 가격이 얼마나 회복됐는지 계산합니다.",
    equation: "((현재가 / 최근 20일 저점) - 1) × 100",
    requiredData: ["priceHistorySeries"],
    outputType: "number",
  },
  {
    key: "volume_spike_bool",
    name: "거래량 급증 여부",
    description: "평소보다 눈에 띄는 거래량 팽창이 있는지 확인합니다.",
    equation: "최근 거래량 > 직전 평균 거래량 × 1.4",
    requiredData: ["volumeHistorySeries"],
    outputType: "boolean",
  },
  {
    key: "volatility_compression_bool",
    name: "변동폭 압축 여부",
    description: "최근 변동폭이 직전 평균보다 눈에 띄게 줄었는지 확인합니다.",
    equation: "최근 평균 변동폭 < 직전 평균 변동폭 × 0.85",
    requiredData: ["volatilityHistorySeries"],
    outputType: "boolean",
  },
  {
    key: "average_range_pct",
    name: "평균 일중 변동폭",
    description: "최근 평균적인 가격 변동폭 수준을 퍼센트로 보여줍니다.",
    equation: "최근 변동폭 시계열 평균",
    requiredData: ["volatilityHistorySeries"],
    outputType: "number",
  },
  {
    key: "revenue_growth_yoy",
    name: "전년 대비 매출 성장률",
    description: "전년 동기 대비 매출이 얼마나 늘거나 줄었는지 나타냅니다.",
    equation: "((이번 기간 매출 / 전년 동기 매출) - 1) × 100",
    requiredData: ["financialStatementSnapshot"],
    outputType: "number",
  },
  {
    key: "margin_change_pct",
    name: "마진 변화율",
    description: "이전 기준 대비 수익성 마진이 얼마나 좋아지거나 나빠졌는지 보여줍니다.",
    equation: "이번 기간 마진 - 이전 기준 마진",
    requiredData: ["financialStatementSnapshot"],
    outputType: "number",
  },
  {
    key: "debt_risk_level",
    name: "부채 위험 수준",
    description: "부채 부담을 낮음·중간·높음으로 단순 분류합니다.",
    equation: "순부채 / 현금흐름 / 차환 부담을 종합한 단계 분류",
    requiredData: ["financialStatementSnapshot"],
    outputType: "string",
  },
  {
    key: "price_inside_entry_zone",
    name: "계획 진입 구간 내부 여부",
    description: "현재 가격이 사용자가 정한 계획 진입 구간 안에 있는지 확인합니다.",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    outputType: "boolean",
  },
  {
    key: "price_beyond_entry_zone",
    name: "계획 진입 구간 이탈 여부",
    description: "현재 가격이 사용자가 정한 계획 진입 구간 밖으로 벗어났는지 확인합니다.",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    outputType: "boolean",
  },
  {
    key: "days_since_last_review",
    name: "마지막 논리 검토 후 경과일",
    description: "마지막으로 투자 논리를 검토한 시점 이후 며칠이 지났는지 계산합니다.",
    equation: "오늘 날짜 - 마지막 논리 검토 시점",
    requiredData: ["lastThesisReviewAt"],
    outputType: "number",
  },
  {
    key: "days_until_earnings",
    name: "실적 발표까지 남은 일수",
    description: "다음 실적 이벤트까지 며칠이 남았는지 계산합니다.",
    equation: "다음 실적일 - 오늘",
    requiredData: ["eventCalendar"],
    outputType: "number",
  },
  {
    key: "thesis_review_stale",
    name: "논리 검토 노후화 여부",
    description: "마지막 논리 검토가 너무 오래되어 다시 봐야 하는지 확인합니다.",
    equation: "마지막 검토 후 경과일 >= 14",
    requiredData: ["lastThesisReviewAt"],
    outputType: "boolean",
  },
  {
    key: "manual_flag_present",
    name: "수동 위험 플래그 존재 여부",
    description: "스냅샷이나 Eye에 수동 위험 플래그가 기록되어 있는지 확인합니다.",
    equation: "수동 위험 플래그 배열 길이 > 0 또는 특정 플래그 포함 여부",
    requiredData: ["manualRiskFlags"],
    outputType: "boolean",
  },
];

export const metricCatalog: MetricDefinition[] = [
  {
    key: "drawdown_from_recent_high",
    name: "최근 고점 대비 하락폭",
    humanMeaning: "종목이 최근 고점 기준선에서 얼마나 내려와 있는지 보여줍니다.",
    formulaKey: "drawdown_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 고점 대비 최소 25% 이상 하락한 종목만 포함합니다."],
    exampleDisplayText: "최근 고점 대비 25% 이상 내려온 상태입니다.",
    missingDataBehavior: "데이터가 없으면 통과로 보지 않고, 데이터 품질을 부분 상태로 표시합니다.",
  },
  {
    key: "near_support",
    name: "지지 구간 근접",
    humanMeaning: "가격이 이전 지지 구간 근처에서 버티는지 보여줍니다.",
    formulaKey: "near_support_bool",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["가격이 이전 지지 구간 근처에서 안정되는지 확인합니다."],
    exampleDisplayText: "가격이 지지 구간 부근에서 안정을 찾는 모습입니다.",
    missingDataBehavior: "경고로 처리하고, 타이밍 판단 근거가 일부 비어 있음을 표시합니다.",
  },
  {
    key: "valuation_discount",
    name: "자기 역사 대비 밸류에이션 할인",
    humanMeaning: "해당 종목의 최근 자기 기준 대비 현재 밸류에이션이 더 싸 보이는지 보여줍니다.",
    formulaKey: "valuation_discount_bool",
    requiredData: ["valuationSnapshot"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["밸류에이션 할인 구간인지 확인합니다."],
    exampleDisplayText: "최근 기준 대비 밸류에이션이 더 매력적인 편입니다.",
    missingDataBehavior: "경고로 처리하고, 검토 중심 구도로 남겨둡니다.",
  },
  {
    key: "relative_strength_vs_spy",
    name: "SPY 대비 상대강도",
    humanMeaning: "종목이 시장 기준 대비 얼마나 강하게 버티는지 보여줍니다.",
    formulaKey: "relative_strength_vs_spy_pct",
    requiredData: ["priceHistorySeries", "benchmarkHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["SPY 대비 상대강도가 -3%보다 낫거나 같은지 확인합니다."],
    exampleDisplayText: "시장 대비 상대강도가 심하게 무너지지는 않고 있습니다.",
    missingDataBehavior: "경고로 처리하되 평가는 계속 진행합니다.",
  },
  {
    key: "distance_from_ma_50",
    name: "50일선 대비 거리",
    humanMeaning: "가격이 중기 추세 기준선에서 얼마나 과도하게 이탈했는지 보여줍니다.",
    formulaKey: "distance_from_ma_50_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["가격이 50일선 아래로 5%보다 더 심하게 밀리지 않았는지 확인합니다."],
    exampleDisplayText: "가격이 50일선에서 과도하게 멀어지지 않은 상태입니다.",
    missingDataBehavior: "경고로 처리하고, 타이밍 확증 근거로는 쓰지 않습니다.",
  },
  {
    key: "distance_from_ma_20",
    name: "20일선 대비 거리",
    humanMeaning: "가격이 단기 추세 기준에서 얼마나 벌어져 있는지 보여줍니다.",
    formulaKey: "distance_from_ma_20_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["가격이 20일선 대비 과열되거나 과도하게 밀리지 않았는지 확인합니다."],
    exampleDisplayText: "단기 추세선과 현재 가격의 벌어짐 정도를 보여줍니다.",
    missingDataBehavior: "경고로 처리하고, 단기 타이밍 판단 신뢰도를 낮춥니다.",
  },
  {
    key: "distance_from_ma_200",
    name: "200일선 대비 거리",
    humanMeaning: "가격이 장기 추세 기준에서 구조적으로 얼마나 이탈했는지 보여줍니다.",
    formulaKey: "distance_from_ma_200_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["가격이 200일선 대비 심하게 눌린 상태인지 확인합니다."],
    exampleDisplayText: "장기 추세 기준에서 현재 위치를 보여줍니다.",
    missingDataBehavior: "경고로 처리하고, 장기 추세 해석의 신뢰도를 낮춥니다.",
  },
  {
    key: "volume_spike",
    name: "거래량 급증",
    humanMeaning: "눈에 띄는 거래량 팽창이 발생했는지 보여줍니다.",
    formulaKey: "volume_spike_bool",
    requiredData: ["volumeHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "future",
    exampleConditions: ["거래량 급증이 있는지 확인합니다."],
    exampleDisplayText: "거래량이 평소보다 크게 늘어난 상태입니다.",
    missingDataBehavior: "보류 처리하고, 향후 확장 대상 지표로 표시합니다.",
  },
  {
    key: "volatility_compression",
    name: "변동폭 압축",
    humanMeaning: "급락 뒤 일중 변동폭이 진정되며 가격이 정리되는지 보여줍니다.",
    formulaKey: "volatility_compression_bool",
    requiredData: ["volatilityHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 변동폭이 직전 평균보다 충분히 압축됐는지 확인합니다."],
    exampleDisplayText: "변동폭이 줄며 가격 움직임이 한 단계 정리되는 모습입니다.",
    missingDataBehavior: "경고로 처리하고, 진정 구도 판단에서는 보조 증거만으로 사용합니다.",
  },
  {
    key: "average_range_pct",
    name: "평균 일중 변동폭",
    humanMeaning: "최근 평균적인 일중 변동폭이 아직 과열 상태인지 보여줍니다.",
    formulaKey: "average_range_pct",
    requiredData: ["volatilityHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 평균 변동폭이 4.5% 이하로 내려왔는지 확인합니다."],
    exampleDisplayText: "일중 흔들림이 과도하게 큰 구간은 지나가고 있습니다.",
    missingDataBehavior: "경고로 처리하고, 타이밍 정교화 대신 보조 판단 근거로만 씁니다.",
  },
  {
    key: "price_return_20d",
    name: "20일 수익률",
    humanMeaning: "최근 한 달 남짓 가격 모멘텀이 얼마나 약하거나 강한지 보여줍니다.",
    formulaKey: "price_return_20d_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 20일 수익률이 -10% 이하로 과도하게 무너졌는지 확인합니다."],
    exampleDisplayText: "최근 20일 동안 가격이 급격히 밀린 상태입니다.",
    missingDataBehavior: "경고로 처리하고, 이벤트 충격 강도 판단을 약하게 봅니다.",
  },
  {
    key: "price_return_60d",
    name: "60일 수익률",
    humanMeaning: "중기 흐름이 여전히 살아 있는지, 아니면 구조적으로 꺾였는지 보여줍니다.",
    formulaKey: "price_return_60d_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 60일 수익률이 아직 0% 이상인지 확인합니다."],
    exampleDisplayText: "중기 흐름은 아직 완전히 꺾이지 않았습니다.",
    missingDataBehavior: "경고로 처리하고, 추세 해석의 신뢰도를 낮춥니다.",
  },
  {
    key: "rebound_from_recent_low",
    name: "최근 저점 대비 반등률",
    humanMeaning: "최근 저점에서 회복이 얼마나 나왔는지 보여줍니다.",
    formulaKey: "rebound_from_recent_low_pct",
    requiredData: ["priceHistorySeries"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["최근 저점에서 최소 5% 이상 회복했는지 확인합니다."],
    exampleDisplayText: "최근 저점 기준 회복 폭을 보여줍니다.",
    missingDataBehavior: "경고로 처리하고, 회복 확인 증거를 약하게 봅니다.",
  },
  {
    key: "revenue_growth_yoy",
    name: "전년 대비 매출 성장률",
    humanMeaning: "사업의 외형이 무너지지 않는지를 보여주는 기초 품질 지표입니다.",
    formulaKey: "revenue_growth_yoy",
    requiredData: ["financialStatementSnapshot"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["전년 대비 매출 성장률이 0% 이상인지 확인합니다."],
    exampleDisplayText: "전년 대비 매출이 무너지는 흐름은 아닙니다.",
    missingDataBehavior: "경고로 처리하고, 품질 신뢰도를 낮춥니다.",
  },
  {
    key: "margin_change_pct",
    name: "마진 변화",
    humanMeaning: "수익성 마진이 안정되는지, 아니면 나빠지는지 보여줍니다.",
    formulaKey: "margin_change_pct",
    requiredData: ["financialStatementSnapshot"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["마진 변화율이 -3%보다 양호한지 확인합니다."],
    exampleDisplayText: "마진이 구조적으로 무너지는 흐름은 아닙니다.",
    missingDataBehavior: "경고로 처리하고, 품질 신뢰도를 낮춥니다.",
  },
  {
    key: "debt_risk_level",
    name: "부채 위험",
    humanMeaning: "부채 부담이 낮은지, 중간인지, 높은지 단순 분류해 보여줍니다.",
    formulaKey: "debt_risk_level",
    requiredData: ["financialStatementSnapshot"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["부채 위험 수준이 높음이 아닌지 확인합니다."],
    exampleDisplayText: "부채 위험이 심각한 수준으로 보이지는 않습니다.",
    missingDataBehavior: "경고로 처리하고, 위험 민감 레시피에서는 수동 검토를 요구합니다.",
  },
  {
    key: "earnings_soon",
    name: "실적 발표까지 남은 기간",
    humanMeaning: "가까운 실적 이벤트가 단기 불확실성을 키우는지 보여줍니다.",
    formulaKey: "earnings_soon_bool",
    requiredData: ["eventCalendar"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["실적 발표가 너무 가까운 구간이 아닌지 확인합니다."],
    exampleDisplayText: "실적 이벤트가 가까워 단기 불확실성이 커진 상태입니다.",
    missingDataBehavior: "경고로 처리하되 평가는 계속 진행합니다.",
  },
  {
    key: "days_until_earnings",
    name: "실적 발표까지 남은 일수",
    humanMeaning: "다음 실적 이벤트까지 얼마나 남았는지 정량으로 보여줍니다.",
    formulaKey: "days_until_earnings",
    requiredData: ["eventCalendar"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["실적 발표까지 최소 7일 이상 남았는지 확인합니다."],
    exampleDisplayText: "다음 실적 이벤트까지 남은 시간을 보여줍니다.",
    missingDataBehavior: "경고로 처리하고, 이벤트 리스크 판단을 약하게 봅니다.",
  },
  {
    key: "price_inside_entry_zone",
    name: "계획 진입 구간 내부",
    humanMeaning: "현재 가격이 사용자가 정한 진입 구간 안에 들어와 있는지 보여줍니다.",
    formulaKey: "price_inside_entry_zone",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    freshnessExpectation: "Daily",
    availability: "manual",
    exampleConditions: ["가격이 계획 진입 구간 안에 있는지 확인합니다."],
    exampleDisplayText: "현재 가격이 계획한 진입 구간 안에 들어와 있습니다.",
    missingDataBehavior: "경고로 처리하고, 진입 구간 타이밍 정보가 비어 있음을 표시합니다.",
  },
  {
    key: "price_beyond_entry_zone",
    name: "계획 진입 구간 이탈",
    humanMeaning: "현재 가격이 계획 진입 구간을 벗어났는지 보여줍니다.",
    formulaKey: "price_beyond_entry_zone",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    freshnessExpectation: "Daily",
    availability: "manual",
    exampleConditions: ["가격이 계획한 진입 구간 밖으로 이탈했는지 확인합니다."],
    exampleDisplayText: "현재 가격이 계획한 진입 구간을 벗어났습니다.",
    missingDataBehavior: "경고로 처리하고, 계획 가격대 정보가 비어 있음을 표시합니다.",
  },
  {
    key: "days_since_last_review",
    name: "마지막 논리 검토 후 경과일",
    humanMeaning: "투자 논리 검토가 얼마나 오래됐는지 보여줍니다.",
    formulaKey: "days_since_last_review",
    requiredData: ["lastThesisReviewAt"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["투자 논리를 최소 14일 이상 다시 보지 않았는지 확인합니다."],
    exampleDisplayText: "이 Eye는 최근 투자 논리 재점검이 없었습니다.",
    missingDataBehavior: "검토 메타데이터 누락으로 처리하고, 재검토를 유도합니다.",
  },
  {
    key: "thesis_review_stale",
    name: "논리 재검토 필요",
    humanMeaning: "논리 검토가 오래되어 재검토가 필요한지 보여줍니다.",
    formulaKey: "thesis_review_stale",
    requiredData: ["lastThesisReviewAt"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["마지막 검토 후 14일 이상 지났는지 확인합니다."],
    exampleDisplayText: "논리 재검토 주기를 넘긴 상태입니다.",
    missingDataBehavior: "검토 이력이 비어 있으면 재검토 필요로 강하게 표시합니다.",
  },
  {
    key: "manual_flag_present",
    name: "수동 강제 제외 플래그",
    humanMeaning: "사용자가 중대한 위험이나 논리 훼손 사건을 수동으로 표시했는지 보여줍니다.",
    formulaKey: "manual_flag_present",
    requiredData: ["manualRiskFlags"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["수동 플래그에 회계 이슈 같은 중대한 위험이 포함됐는지 확인합니다."],
    exampleDisplayText: "수동 강제 제외 플래그가 기록되어 있습니다.",
    missingDataBehavior: "위험이 없다고 가정하지 않습니다. 명시적으로 없을 때만 통과로 봅니다.",
  },
];

export const getMetricDefinition = (metricKey?: string) =>
  metricKey ? metricCatalog.find((metric) => metric.key === metricKey) : undefined;

export const getFormulaDefinition = (formulaKey?: string) =>
  formulaKey ? formulaRegistry.find((formula) => formula.key === formulaKey) : undefined;
