import { FormulaDefinition, MetricDefinition } from "../types";

export const formulaRegistry: FormulaDefinition[] = [
  {
    key: "drawdown_pct",
    name: "Drawdown Percent",
    description: "Current price compared with a recent high baseline.",
    requiredData: ["price", "drawdownPct"],
    outputType: "number",
  },
  {
    key: "near_support_bool",
    name: "Near Support",
    description: "Whether price is stabilizing near a support zone.",
    requiredData: ["nearSupport"],
    outputType: "boolean",
  },
  {
    key: "stabilization_score",
    name: "Stabilization Score",
    description: "Simplified selling-pressure cooling score.",
    requiredData: ["stabilizationScore"],
    outputType: "number",
  },
  {
    key: "valuation_discount_bool",
    name: "Valuation Discount",
    description: "Whether valuation looks cheaper than its recent baseline.",
    requiredData: ["valuationDiscount"],
    outputType: "boolean",
  },
  {
    key: "analyst_revision_trend",
    name: "Analyst Revision Trend",
    description: "Placeholder improving / flat / weak revisions signal.",
    requiredData: ["analystRevisionTrend"],
    outputType: "string",
  },
  {
    key: "earnings_soon_bool",
    name: "Earnings Soon",
    description: "Whether a near earnings event increases uncertainty.",
    requiredData: ["earningsSoon"],
    outputType: "boolean",
  },
  {
    key: "relative_strength_vs_spy_pct",
    name: "Relative Strength vs SPY",
    description: "Stock performance versus market benchmark over a lookback.",
    requiredData: ["relativeStrengthVsSpyPct"],
    outputType: "number",
  },
  {
    key: "distance_from_ma_50_pct",
    name: "Distance from 50-Day Moving Average",
    description: "Current price relative to a 50-day average baseline.",
    requiredData: ["movingAverage50DistancePct"],
    outputType: "number",
  },
  {
    key: "volume_spike_bool",
    name: "Volume Spike",
    description: "Whether notable volume activity is present.",
    requiredData: ["volumeSpike"],
    outputType: "boolean",
  },
  {
    key: "revenue_growth_yoy",
    name: "Revenue Growth YoY",
    description: "Year-over-year revenue growth placeholder.",
    requiredData: ["revenueGrowthYoY"],
    outputType: "number",
  },
  {
    key: "margin_change_pct",
    name: "Margin Change Percent",
    description: "Margin trend placeholder relative to prior baseline.",
    requiredData: ["marginChangePct"],
    outputType: "number",
  },
  {
    key: "debt_risk_level",
    name: "Debt Risk Level",
    description: "Simplified debt-risk classification.",
    requiredData: ["debtRiskLevel"],
    outputType: "string",
  },
  {
    key: "price_inside_entry_zone",
    name: "Price Inside Planned Entry Zone",
    description: "Whether current price is inside the user-defined planned entry range.",
    requiredData: ["price", "plannedEntryLow", "plannedEntryHigh"],
    outputType: "boolean",
  },
  {
    key: "days_since_last_review",
    name: "Days Since Last Thesis Review",
    description: "Current date minus the last thesis review date.",
    requiredData: ["lastThesisReviewAt"],
    outputType: "number",
  },
  {
    key: "manual_flag_present",
    name: "Manual Flag Present",
    description: "Whether a named manual risk flag exists in the snapshot or Eye flags.",
    requiredData: ["riskFlags"],
    outputType: "boolean",
  },
];

export const metricCatalog: MetricDefinition[] = [
  {
    key: "drawdown_from_recent_high",
    name: "Drawdown from Recent High",
    humanMeaning: "How far the stock is below its recent high baseline.",
    formulaKey: "drawdown_pct",
    requiredData: ["price", "drawdownPct"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Stock is down at least 25% from its recent high."],
    exampleDisplayText: "Stock is down at least 25 percent from its recent high.",
    missingDataBehavior: "Do not pass the condition. Mark data quality as partial.",
  },
  {
    key: "near_support",
    name: "Near Support",
    humanMeaning: "Whether price is holding near a prior support zone.",
    formulaKey: "near_support_bool",
    requiredData: ["nearSupport"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Price is stabilizing near prior support."],
    exampleDisplayText: "Price is stabilizing near prior support.",
    missingDataBehavior: "Warn and treat as missing timing context.",
  },
  {
    key: "stabilization_score",
    name: "Selling Pressure Cooling",
    humanMeaning: "Whether the selloff looks like it is cooling rather than accelerating.",
    formulaKey: "stabilization_score",
    requiredData: ["stabilizationScore"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Selling pressure cooling score is at least 65."],
    exampleDisplayText: "Selling pressure is showing early signs of stabilization.",
    missingDataBehavior: "Warn and reduce setup confidence.",
  },
  {
    key: "valuation_discount",
    name: "Valuation Discount vs Own History",
    humanMeaning: "Whether valuation looks cheaper than the stock's own recent baseline.",
    formulaKey: "valuation_discount_bool",
    requiredData: ["valuationDiscount"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Valuation discount is present."],
    exampleDisplayText: "Valuation looks more attractive than the recent baseline.",
    missingDataBehavior: "Warn and keep the setup review-oriented.",
  },
  {
    key: "analyst_revision_trend",
    name: "Analyst Revision Trend",
    humanMeaning: "Whether analyst revisions are improving, flat, or weak.",
    formulaKey: "analyst_revision_trend",
    requiredData: ["analystRevisionTrend"],
    freshnessExpectation: "Daily",
    availability: "future",
    exampleConditions: ['Analyst revision trend is not "weak".'],
    exampleDisplayText: "Analyst revisions are not deteriorating.",
    missingDataBehavior: "Warn and leave as future/deferred where unavailable.",
  },
  {
    key: "relative_strength_vs_spy",
    name: "Relative Strength vs SPY",
    humanMeaning: "How the stock is performing versus the market benchmark.",
    formulaKey: "relative_strength_vs_spy_pct",
    requiredData: ["relativeStrengthVsSpyPct"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Relative strength vs SPY is above -3%."],
    exampleDisplayText: "Relative strength versus the market is not deteriorating badly.",
    missingDataBehavior: "Warn and allow evaluation to continue.",
  },
  {
    key: "distance_from_ma_50",
    name: "Distance from 50-Day Moving Average",
    humanMeaning: "How stretched price is relative to an intermediate trend baseline.",
    formulaKey: "distance_from_ma_50_pct",
    requiredData: ["movingAverage50DistancePct"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Price is no worse than 5% below the 50-day average."],
    exampleDisplayText: "Price is holding within a reasonable distance of the 50-day average.",
    missingDataBehavior: "Warn and avoid using it as timing proof.",
  },
  {
    key: "volume_spike",
    name: "Volume Spike",
    humanMeaning: "Whether notable volume expansion is present.",
    formulaKey: "volume_spike_bool",
    requiredData: ["volumeSpike"],
    freshnessExpectation: "Daily",
    availability: "future",
    exampleConditions: ["Volume spike is present."],
    exampleDisplayText: "Volume activity is elevated.",
    missingDataBehavior: "Defer and mark as future/deferred.",
  },
  {
    key: "revenue_growth_yoy",
    name: "Revenue Growth YoY",
    humanMeaning: "Simple business-quality proxy for top-line health.",
    formulaKey: "revenue_growth_yoy",
    requiredData: ["revenueGrowthYoY"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Revenue growth remains above 0% YoY."],
    exampleDisplayText: "Revenue is not collapsing year over year.",
    missingDataBehavior: "Warn and reduce quality confidence.",
  },
  {
    key: "margin_change_pct",
    name: "Margin Change",
    humanMeaning: "Whether margins are stabilizing or deteriorating.",
    formulaKey: "margin_change_pct",
    requiredData: ["marginChangePct"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Margin change is better than -3%."],
    exampleDisplayText: "Margins are not structurally breaking.",
    missingDataBehavior: "Warn and reduce quality confidence.",
  },
  {
    key: "debt_risk_level",
    name: "Debt Risk",
    humanMeaning: "Simplified debt stress classification.",
    formulaKey: "debt_risk_level",
    requiredData: ["debtRiskLevel"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Debt risk level is not high."],
    exampleDisplayText: "Debt risk does not look severe.",
    missingDataBehavior: "Warn and require manual review for risk-sensitive recipes.",
  },
  {
    key: "earnings_soon",
    name: "Days Until Earnings",
    humanMeaning: "Whether a near event introduces additional short-term uncertainty.",
    formulaKey: "earnings_soon_bool",
    requiredData: ["earningsSoon"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["Earnings are not within the near-term event window."],
    exampleDisplayText: "An earnings event is close, which raises short-term uncertainty.",
    missingDataBehavior: "Warn and allow evaluation to continue.",
  },
  {
    key: "price_inside_entry_zone",
    name: "Price Inside Planned Entry Zone",
    humanMeaning: "Whether price is inside the user's intended entry area.",
    formulaKey: "price_inside_entry_zone",
    requiredData: ["price", "plannedEntryLow", "plannedEntryHigh"],
    freshnessExpectation: "Daily",
    availability: "manual",
    exampleConditions: ["Price is inside the planned entry zone."],
    exampleDisplayText: "Price is inside the planned entry zone.",
    missingDataBehavior: "Warn and mark entry-zone timing as missing.",
  },
  {
    key: "days_since_last_review",
    name: "Days Since Last Thesis Review",
    humanMeaning: "How stale the thesis review is.",
    formulaKey: "days_since_last_review",
    requiredData: ["lastThesisReviewAt"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["Thesis has not been reviewed in at least 14 days."],
    exampleDisplayText: "This Eye has not had a recent thesis review.",
    missingDataBehavior: "Treat as missing review metadata and prompt review.",
  },
  {
    key: "manual_flag_present",
    name: "Manual Hard Disqualifier Flag",
    humanMeaning: "Whether the user marked a serious manual risk or thesis-break event.",
    formulaKey: "manual_flag_present",
    requiredData: ["riskFlags"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["Manual flag includes accounting issue."],
    exampleDisplayText: "A manual hard disqualifier flag is present.",
    missingDataBehavior: "Do not assume no risk. Only pass if explicitly absent.",
  },
];

export const getMetricDefinition = (metricKey?: string) =>
  metricKey ? metricCatalog.find((metric) => metric.key === metricKey) : undefined;

export const getFormulaDefinition = (formulaKey?: string) =>
  formulaKey ? formulaRegistry.find((formula) => formula.key === formulaKey) : undefined;
