import { AppData, Recipe } from "../types";

const now = new Date().toISOString();

const starterRecipe = (recipe: Recipe): Recipe => recipe;

export const seedData: AppData = {
  stocks: [
    {
      id: "stock-amd",
      symbol: "AMD",
      name: "Advanced Micro Devices",
      thesis:
        "High-quality semiconductor leader worth watching for a temporary bargain setup after a broad pullback.",
      createdAt: now,
    },
    {
      id: "stock-meli",
      symbol: "MELI",
      name: "MercadoLibre",
      thesis:
        "High-conviction compounder that can become interesting if a growth scare creates a temporary reset instead of structural damage.",
      createdAt: now,
    },
    {
      id: "stock-uber",
      symbol: "UBER",
      name: "Uber Technologies",
      thesis:
        "Execution story with improving profitability. Worth monitoring for either a quality pullback or thesis-risk deterioration.",
      createdAt: now,
    },
    {
      id: "stock-nvda",
      symbol: "NVDA",
      name: "NVIDIA",
      thesis:
        "Sector leader that may become interesting on a controlled pullback with continued relative strength.",
      createdAt: now,
    },
  ],
  recipes: [
    starterRecipe({
      id: "recipe-bargain-sale",
      version: 1,
      name: "Temporary Bargain Sale",
      purpose:
        "Spot a good company that looks temporarily mispriced after a meaningful decline and early stabilization.",
      opportunityType: "Temporary mispricing in a quality business",
      timeHorizon: "Multi-week to multi-month",
      intendedUseCase: "Quality business in a temporary reset, not a structurally broken company.",
      notes:
        "Use for watchlist names you already trust. Avoid treating a collapsing business as a bargain.",
      createdAt: now,
      stateConfig: {
        attentionNeededMinScore: 5,
        opportunityMinScore: 4,
        watchMinScore: 3,
        becomingInterestingMinScore: 1,
        riskWarningThreshold: 2,
      },
      alertConfig: {
        cooldownHours: 24,
        dedupeKey: "state_change",
        priorityOnAttention: "High",
        priorityOnRisk: "High",
      },
      reviewConfig: {
        cadenceDays: 7,
        reviewTriggers: ["earnings_soon", "days_since_last_review"],
      },
      outcomeConfig: {
        trackedTags: ["entry_zone", "stabilization", "valuation", "risk_check"],
      },
      conditions: [
        {
          id: "c1",
          label: "Stock is down at least 25 percent from its recent high.",
          humanDescription: "Stock is down at least 25 percent from its recent high.",
          kind: "required",
          role: "Eligibility Filter",
          metricKey: "drawdown_from_recent_high",
          formulaKey: "drawdown_pct",
          operator: "<=",
          value: -25,
          unit: "percent",
          availability: "automated",
        },
        {
          id: "c2",
          label: "Valuation discount is present.",
          humanDescription: "Valuation looks cheaper than its own recent baseline.",
          kind: "supporting",
          role: "Supporting Evidence",
          metricKey: "valuation_discount",
          formulaKey: "valuation_discount_bool",
          operator: "is",
          value: true,
          availability: "automated",
        },
        {
          id: "c3",
          label: "Revenue has not collapsed.",
          humanDescription: "Revenue growth is still above zero year over year.",
          kind: "supporting",
          role: "Supporting Evidence",
          metricKey: "revenue_growth_yoy",
          formulaKey: "revenue_growth_yoy",
          operator: ">=",
          value: 0,
          unit: "percent",
          availability: "automated",
        },
        {
          id: "c4",
          label: "Selling pressure is cooling.",
          humanDescription: "Selling pressure cooling score is at least 65.",
          kind: "supporting",
          role: "Timing Trigger",
          metricKey: "stabilization_score",
          formulaKey: "stabilization_score",
          operator: ">=",
          value: 65,
          availability: "automated",
        },
        {
          id: "c5",
          label: "Price is inside the planned entry zone.",
          humanDescription: "Price is inside the planned entry zone.",
          kind: "supporting",
          role: "Timing Trigger",
          metricKey: "price_inside_entry_zone",
          formulaKey: "price_inside_entry_zone",
          operator: "is",
          value: true,
          availability: "manual",
        },
        {
          id: "c6",
          label: "Earnings are not too close.",
          humanDescription: "An earnings event is not immediately ahead of the setup.",
          kind: "negative",
          role: "Risk Warning",
          metricKey: "earnings_soon",
          formulaKey: "earnings_soon_bool",
          operator: "is",
          value: true,
          availability: "automated",
        },
        {
          id: "c7",
          label: "Manual thesis-break flag is absent.",
          humanDescription: "No manual hard disqualifier flag such as accounting issue is present.",
          kind: "disqualifier",
          role: "Hard Disqualifier",
          metricKey: "manual_flag_present",
          formulaKey: "manual_flag_present",
          operator: "is",
          value: true,
          availability: "manual",
        },
      ],
    }),
    starterRecipe({
      id: "recipe-sector-leader-pullback",
      version: 1,
      name: "Sector Leader Pullback",
      purpose: "Watch for controlled pullbacks in category leaders that still hold up versus the market.",
      opportunityType: "Quality leader in controlled pullback",
      timeHorizon: "Multi-week",
      intendedUseCase: "Leader stock that resets without losing relative strength or trend structure.",
      notes: "Best used for proven leaders rather than speculative names.",
      createdAt: now,
      stateConfig: {
        attentionNeededMinScore: 5,
        opportunityMinScore: 4,
        watchMinScore: 3,
        becomingInterestingMinScore: 1,
        riskWarningThreshold: 2,
      },
      alertConfig: {
        cooldownHours: 24,
        dedupeKey: "state_change",
        priorityOnAttention: "High",
        priorityOnRisk: "Medium",
      },
      reviewConfig: {
        cadenceDays: 10,
        reviewTriggers: ["days_since_last_review"],
      },
      outcomeConfig: {
        trackedTags: ["relative_strength", "trend_hold"],
      },
      conditions: [
        {
          id: "c8",
          label: "Drawdown is meaningful but not destructive.",
          humanDescription: "Stock is down at least 10 percent from its recent high.",
          kind: "required",
          role: "Eligibility Filter",
          metricKey: "drawdown_from_recent_high",
          formulaKey: "drawdown_pct",
          operator: "<=",
          value: -10,
          availability: "automated",
        },
        {
          id: "c9",
          label: "Relative strength remains resilient.",
          humanDescription: "Relative strength versus SPY is no worse than negative 3 percent.",
          kind: "supporting",
          role: "Supporting Evidence",
          metricKey: "relative_strength_vs_spy",
          formulaKey: "relative_strength_vs_spy_pct",
          operator: ">=",
          value: -3,
          availability: "automated",
        },
        {
          id: "c10",
          label: "Price is not badly below the 50-day moving average.",
          humanDescription: "Price is within 5 percent of the 50-day moving average.",
          kind: "supporting",
          role: "Timing Trigger",
          metricKey: "distance_from_ma_50",
          formulaKey: "distance_from_ma_50_pct",
          operator: ">=",
          value: -5,
          availability: "automated",
        },
      ],
    }),
    starterRecipe({
      id: "recipe-bad-news-overreaction",
      version: 1,
      name: "Bad News Overreaction",
      purpose: "Separate temporary panic from structural damage after a sharp negative reaction.",
      opportunityType: "Overreaction to a news/event shock",
      timeHorizon: "Multi-day to multi-week",
      intendedUseCase: "Useful when a stock gaps down hard but the thesis may still be intact.",
      notes: "Requires extra care around hidden structural damage.",
      createdAt: now,
      stateConfig: {
        attentionNeededMinScore: 5,
        opportunityMinScore: 4,
        watchMinScore: 3,
        becomingInterestingMinScore: 1,
        riskWarningThreshold: 1,
      },
      alertConfig: {
        cooldownHours: 12,
        dedupeKey: "state_change",
        priorityOnAttention: "High",
        priorityOnRisk: "High",
      },
      reviewConfig: {
        cadenceDays: 3,
        reviewTriggers: ["earnings_soon", "days_since_last_review"],
      },
      outcomeConfig: {
        trackedTags: ["gap_down", "thesis_recheck"],
      },
      conditions: [
        {
          id: "c11",
          label: "Drawdown is sharp enough to matter.",
          humanDescription: "Stock is down at least 20 percent from its recent high.",
          kind: "required",
          role: "Eligibility Filter",
          metricKey: "drawdown_from_recent_high",
          formulaKey: "drawdown_pct",
          operator: "<=",
          value: -20,
          availability: "automated",
        },
        {
          id: "c12",
          label: "Manual hard disqualifier flag must be absent.",
          humanDescription: "No manual severe-risk flag is present.",
          kind: "disqualifier",
          role: "Hard Disqualifier",
          metricKey: "manual_flag_present",
          formulaKey: "manual_flag_present",
          operator: "is",
          value: true,
          availability: "manual",
        },
      ],
    }),
    starterRecipe({
      id: "recipe-earnings-reset-recovery",
      version: 1,
      name: "Earnings Reset Recovery",
      purpose: "Watch for recovery setups after an earnings-related reset that may have gone too far.",
      opportunityType: "Post-earnings reset recovery",
      timeHorizon: "Multi-day to multi-week",
      intendedUseCase: "Useful when earnings shock reprices expectations but the thesis may recover.",
      notes: "Requires close review of earnings/event risk and follow-through.",
      createdAt: now,
      stateConfig: {
        attentionNeededMinScore: 5,
        opportunityMinScore: 4,
        watchMinScore: 3,
        becomingInterestingMinScore: 1,
        riskWarningThreshold: 2,
      },
      alertConfig: {
        cooldownHours: 24,
        dedupeKey: "state_change",
        priorityOnAttention: "High",
        priorityOnRisk: "Medium",
      },
      reviewConfig: {
        cadenceDays: 5,
        reviewTriggers: ["days_since_last_review"],
      },
      outcomeConfig: {
        trackedTags: ["earnings_reset", "stabilization_followthrough"],
      },
      conditions: [
        {
          id: "c13",
          label: "There has been a meaningful reset.",
          humanDescription: "Stock is down at least 15 percent from its recent high.",
          kind: "required",
          role: "Eligibility Filter",
          metricKey: "drawdown_from_recent_high",
          formulaKey: "drawdown_pct",
          operator: "<=",
          value: -15,
          availability: "automated",
        },
        {
          id: "c14",
          label: "Stabilization is improving after the reset.",
          humanDescription: "Selling pressure cooling score is at least 60.",
          kind: "supporting",
          role: "Timing Trigger",
          metricKey: "stabilization_score",
          formulaKey: "stabilization_score",
          operator: ">=",
          value: 60,
          availability: "automated",
        },
      ],
    }),
  ],
  eyes: [
    {
      id: "eye-amd-bargain",
      stockId: "stock-amd",
      recipeId: "recipe-bargain-sale",
      recipeVersionAtCreation: 1,
      thesisSnapshot:
        "Watch for a quality-led pullback that becomes attractive only if selling pressure slows and no structural damage appears.",
      plannedEntryLow: 136,
      plannedEntryHigh: 145,
      createdAt: now,
      lastReviewedAt: now,
    },
    {
      id: "eye-meli-bargain",
      stockId: "stock-meli",
      recipeId: "recipe-bargain-sale",
      recipeVersionAtCreation: 1,
      thesisSnapshot:
        "Growth compounder worth attention if macro pressure creates discount without harming the long-run business case.",
      plannedEntryLow: 1600,
      plannedEntryHigh: 1680,
      createdAt: now,
      lastReviewedAt: now,
    },
    {
      id: "eye-uber-risk",
      stockId: "stock-uber",
      recipeId: "recipe-bad-news-overreaction",
      recipeVersionAtCreation: 1,
      thesisSnapshot:
        "If execution momentum weakens and risk flags rise, treat the setup as a thesis check rather than a dip-buy signal.",
      plannedEntryLow: 70,
      plannedEntryHigh: 75,
      manualFlags: ["guidance_pressure"],
      createdAt: now,
      lastReviewedAt: now,
    },
    {
      id: "eye-nvda-leader",
      stockId: "stock-nvda",
      recipeId: "recipe-sector-leader-pullback",
      recipeVersionAtCreation: 1,
      thesisSnapshot:
        "Monitor for a controlled pullback where relative strength remains strong enough to keep the leader thesis intact.",
      plannedEntryLow: 1130,
      plannedEntryHigh: 1185,
      createdAt: now,
      lastReviewedAt: now,
    },
  ],
  alerts: [],
  decisions: [],
  outcomes: [],
  snapshots: [
    {
      stockId: "stock-amd",
      price: 142.35,
      drawdownPct: -28,
      nearSupport: true,
      stabilizationScore: 71,
      valuationDiscount: true,
      analystRevisionTrend: "flat",
      earningsSoon: true,
      riskFlags: [],
      movingAverage50DistancePct: -2.1,
      relativeStrengthVsSpyPct: -1.8,
      volumeSpike: false,
      revenueGrowthYoY: 4,
      marginChangePct: -1,
      debtRiskLevel: "low",
      plannedEntryLow: 136,
      plannedEntryHigh: 145,
      lastThesisReviewAt: now,
      updatedAt: now,
      sourceName: "Mock Market Adapter",
      freshness: "Mock Data",
      isMock: true,
    },
    {
      stockId: "stock-meli",
      price: 1648.2,
      drawdownPct: -23,
      nearSupport: true,
      stabilizationScore: 67,
      valuationDiscount: true,
      analystRevisionTrend: "improving",
      earningsSoon: false,
      riskFlags: [],
      movingAverage50DistancePct: 1.4,
      relativeStrengthVsSpyPct: 2.2,
      volumeSpike: false,
      revenueGrowthYoY: 18,
      marginChangePct: 1,
      debtRiskLevel: "low",
      plannedEntryLow: 1600,
      plannedEntryHigh: 1680,
      lastThesisReviewAt: now,
      updatedAt: now,
      sourceName: "Mock Market Adapter",
      freshness: "Mock Data",
      isMock: true,
    },
    {
      stockId: "stock-uber",
      price: 73.18,
      drawdownPct: -14,
      nearSupport: false,
      stabilizationScore: 44,
      valuationDiscount: false,
      analystRevisionTrend: "weak",
      earningsSoon: true,
      riskFlags: ["guidance_pressure"],
      movingAverage50DistancePct: -7.8,
      relativeStrengthVsSpyPct: -5.5,
      volumeSpike: true,
      revenueGrowthYoY: 8,
      marginChangePct: -4,
      debtRiskLevel: "medium",
      plannedEntryLow: 70,
      plannedEntryHigh: 75,
      lastThesisReviewAt: now,
      updatedAt: now,
      sourceName: "Mock Market Adapter",
      freshness: "Mock Data",
      isMock: true,
    },
    {
      stockId: "stock-nvda",
      price: 1164.5,
      drawdownPct: -12,
      nearSupport: true,
      stabilizationScore: 63,
      valuationDiscount: false,
      analystRevisionTrend: "improving",
      earningsSoon: false,
      riskFlags: [],
      movingAverage50DistancePct: -1.9,
      relativeStrengthVsSpyPct: 4.2,
      volumeSpike: false,
      revenueGrowthYoY: 28,
      marginChangePct: 3,
      debtRiskLevel: "low",
      plannedEntryLow: 1130,
      plannedEntryHigh: 1185,
      lastThesisReviewAt: now,
      updatedAt: now,
      sourceName: "Mock Market Adapter",
      freshness: "Mock Data",
      isMock: true,
    },
  ],
};
