import { AppData, Recipe, MetricDefinition, LogicRule, LogicSet } from "../types";

const now = new Date().toISOString();
const daysAgo = (days: number, hours = 0) =>
  new Date(Date.now() - (days * 24 + hours) * 60 * 60 * 1000).toISOString();

const starterCustomMetrics: MetricDefinition[] = [
  {
    key: "metric_drawdown_from_252d_high",
    name: "252일 고점 대비 하락률",
    humanMeaning: "현재 가격이 최근 252거래일 고점에서 얼마나 밀려 있는지 퍼센트로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_HIGH_252D )",
    parameterKeys: ["PRICE_NOW", "PRICE_HIGH_252D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["252일 고점 대비 하락률이 -20% 이하인지 확인합니다."],
    exampleDisplayText: "장기 고점 기준으로 현재 낙폭을 계산합니다.",
    missingDataBehavior: "장기 가격 이력이 부족하면 계산하지 않고 데이터 부족으로 남깁니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_price_vs_50d_gap",
    name: "현재가-50일선 괴리율",
    humanMeaning: "현재 가격이 50일 평균가 대비 얼마나 위나 아래에 있는지 백분율로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_AVG_50D )",
    parameterKeys: ["PRICE_NOW", "PRICE_AVG_50D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["현재가-50일선 괴리율이 -4% 이상인지 확인합니다."],
    exampleDisplayText: "현재 가격이 50일선보다 얼마나 눌리거나 과열됐는지 보여줍니다.",
    missingDataBehavior: "가격 시계열이 비면 계산하지 않고 보조 지표로만 남깁니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_price_vs_200d_gap",
    name: "현재가-200일선 괴리율",
    humanMeaning: "현재 가격이 200일 평균가 대비 얼마나 멀어져 있는지 장기 구조 기준으로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_AVG_200D )",
    parameterKeys: ["PRICE_NOW", "PRICE_AVG_200D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["현재가-200일선 괴리율이 -12% 이하인지 확인합니다."],
    exampleDisplayText: "장기 추세선 대비 현재 위치를 퍼센트로 보여줍니다.",
    missingDataBehavior: "장기 시계열이 부족하면 계산하지 않고 경고로 남깁니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_60d_relative_return",
    name: "60일 상대수익률 스프레드",
    humanMeaning: "최근 60일 동안 종목 수익률이 벤치마크보다 얼마나 더 좋거나 나빴는지 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries", "benchmarkHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_60D_AGO ) - PCT_CHANGE ( BENCH_NOW , BENCH_60D_AGO )",
    parameterKeys: ["PRICE_NOW", "PRICE_60D_AGO", "BENCH_NOW", "BENCH_60D_AGO"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["60일 상대수익률 스프레드가 0 이상인지 확인합니다."],
    exampleDisplayText: "최근 60일 기준 시장 대비 초과수익을 보여줍니다.",
    missingDataBehavior: "종목 또는 벤치마크 시계열이 비면 상대비교를 보류합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_20d_momentum",
    name: "20일 가격 모멘텀",
    humanMeaning: "현재 가격이 20거래일 전 대비 얼마나 움직였는지 퍼센트로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_20D_AGO )",
    parameterKeys: ["PRICE_NOW", "PRICE_20D_AGO"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["20일 가격 모멘텀이 -8% 이하인지 확인합니다."],
    exampleDisplayText: "최근 한 달 가까운 가격 변화율을 보여줍니다.",
    missingDataBehavior: "단기 가격 이력이 부족하면 계산하지 않습니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_rebound_from_20d_low",
    name: "20일 저점 대비 반등률",
    humanMeaning: "현재 가격이 최근 20거래일 저점에서 얼마나 회복됐는지 퍼센트로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries"],
    expression: "PCT_CHANGE ( PRICE_NOW , PRICE_LOW_20D )",
    parameterKeys: ["PRICE_NOW", "PRICE_LOW_20D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["20일 저점 대비 반등률이 5% 이상인지 확인합니다."],
    exampleDisplayText: "단기 저점 기준 회복 속도를 보여줍니다.",
    missingDataBehavior: "단기 가격 이력이 없으면 회복 판단을 보류합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_volume_burst_ratio",
    name: "거래량 급증 배수",
    humanMeaning: "현재 거래량이 최근 20일 평균 대비 몇 배인지 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["volumeHistorySeries"],
    expression: "VOL_NOW / VOL_AVG_20D",
    parameterKeys: ["VOL_NOW", "VOL_AVG_20D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["거래량 급증 배수가 1.8 이상인지 확인합니다."],
    exampleDisplayText: "평균 거래량 대비 현재 거래량의 팽창 정도를 보여줍니다.",
    missingDataBehavior: "거래량 평균이 없으면 계산하지 않고 보조 증거에서 제외합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_volatility_cooling_rate",
    name: "변동폭 냉각률",
    humanMeaning: "최근 10일 평균 변동폭이 30일 평균 대비 얼마나 진정됐는지 퍼센트로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["volatilityHistorySeries"],
    expression: "PCT_CHANGE ( RANGE_AVG_10D , RANGE_AVG_30D )",
    parameterKeys: ["RANGE_AVG_10D", "RANGE_AVG_30D"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["변동폭 냉각률이 -10% 이하인지 확인합니다."],
    exampleDisplayText: "최근 일중 변동폭이 직전 평균보다 얼마나 줄었는지 보여줍니다.",
    missingDataBehavior: "변동폭 시계열이 부족하면 진정 판단을 보류합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_entry_mid_gap",
    name: "진입 구간 중간값 대비 괴리율",
    humanMeaning: "현재 가격이 계획한 진입 구간의 중간값에서 얼마나 벗어났는지 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    expression: "PCT_CHANGE ( PRICE_NOW , AVG ( ENTRY_LOW , ENTRY_HIGH ) )",
    parameterKeys: ["PRICE_NOW", "ENTRY_LOW", "ENTRY_HIGH"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["진입 구간 중간값 대비 괴리율이 -3%에서 3% 사이인지 확인합니다."],
    exampleDisplayText: "현재 가격이 사용자의 진입 계획 중심값에 얼마나 가까운지 보여줍니다.",
    missingDataBehavior: "진입 구간이 비어 있으면 계산하지 않고 수동 입력 필요로 표시합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_entry_center_distance",
    name: "진입 구간 중심 이탈 절대값",
    humanMeaning: "현재 가격이 계획 진입 구간 중심값에서 얼마나 벗어났는지 절대 편차로 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["priceHistorySeries", "plannedEntryRange"],
    expression: "ABS ( PCT_CHANGE ( PRICE_NOW , AVG ( ENTRY_LOW , ENTRY_HIGH ) ) )",
    parameterKeys: ["PRICE_NOW", "ENTRY_LOW", "ENTRY_HIGH"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["진입 구간 중심 이탈 절대값이 5 이하인지 확인합니다."],
    exampleDisplayText: "가격이 계획 중심값에서 얼마나 벗어났는지 절대 편차로 보여줍니다.",
    missingDataBehavior: "진입 구간이 없으면 계산하지 않고 수동 입력 필요로 둡니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_review_staleness_ratio",
    name: "논리 검토 경과 비율",
    humanMeaning: "마지막 논리 검토 이후 경과일이 기준 14일 대비 얼마나 쌓였는지 보여줍니다.",
    formulaKey: "custom_expression",
    requiredData: ["lastThesisReviewAt"],
    expression: "REVIEW_DAYS / 14",
    parameterKeys: ["REVIEW_DAYS"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["논리 검토 경과 비율이 1 이상인지 확인합니다."],
    exampleDisplayText: "논리 재검토가 얼마나 밀렸는지 비율로 보여줍니다.",
    missingDataBehavior: "검토 기록이 없으면 경고로 남기고 수동 검토를 요구합니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_event_pressure_score",
    name: "이벤트 임박 압박 점수",
    humanMeaning: "실적 발표가 2주 안으로 들어올수록 압박이 커지도록 0~100 범위로 압축한 점수입니다.",
    formulaKey: "custom_expression",
    requiredData: ["eventCalendar"],
    expression: "CLAMP ( ( 14 - EARN_DAYS ) / 14 * 100 , 0 , 100 )",
    parameterKeys: ["EARN_DAYS"],
    freshnessExpectation: "Daily",
    availability: "automated",
    exampleConditions: ["이벤트 임박 압박 점수가 50 이상인지 확인합니다."],
    exampleDisplayText: "실적 발표가 가까워질수록 경계 강도가 높아지는 점수입니다.",
    missingDataBehavior: "이벤트 일정이 비면 계산하지 않고 이벤트 확인 필요로 둡니다.",
    origin: "custom",
    createdAt: now,
  },
  {
    key: "metric_manual_risk_pressure",
    name: "수동 위험 압박 점수",
    humanMeaning: "수동 위험 플래그 수를 0~100 압박 점수로 단순 환산합니다.",
    formulaKey: "custom_expression",
    requiredData: ["manualRiskFlags"],
    expression: "CLAMP ( FLAG_COUNT * 25 , 0 , 100 )",
    parameterKeys: ["FLAG_COUNT"],
    freshnessExpectation: "Review Cadence",
    availability: "manual",
    exampleConditions: ["수동 위험 압박 점수가 25 이상인지 확인합니다."],
    exampleDisplayText: "사용자가 기록한 위험 플래그 강도를 점수화해 보여줍니다.",
    missingDataBehavior: "위험 플래그가 없으면 0으로 간주합니다.",
    origin: "custom",
    createdAt: now,
  },
];

const seedRecipes: Recipe[] = [
  {
    id: "recipe-bargain-sale",
    lineageId: "recipe-bargain-sale",
    version: 1,
    name: "Temporary Bargain Sale",
    purpose: "Catch high quality companies when a sharp drawdown creates a temporary mispricing.",
    opportunityType: "Temporary Mispricing",
    timeHorizon: "1 to 3 months",
    intendedUseCase: "Watchlist Triage",
    notes: "Focus on deep damage with still-acceptable business quality and a usable entry zone.",
    createdAt: now,
    reviewConfig: { cadenceDays: 7, reviewTriggers: ["earnings_soon"] },
    alertConfig: { cooldownHours: 24, dedupeKey: "state_change", priorityOnAttention: "High", priorityOnRisk: "High" },
    conditions: [
      { id: "c1", label: "Deep Drawdown", kind: "required", role: "Eligibility Filter", metricKey: "metric_drawdown_from_252d_high", formulaKey: "custom_expression", operator: "<=", value: -25, availability: "automated" },
      { id: "c1b", label: "Long Trend Dislocation", kind: "supporting", role: "Supporting Evidence", metricKey: "metric_price_vs_200d_gap", formulaKey: "custom_expression", operator: "<=", value: -12, availability: "automated" },
      { id: "c1c", label: "Volatility Cooling", kind: "supporting", role: "Timing Trigger", metricKey: "metric_volatility_cooling_rate", formulaKey: "custom_expression", operator: "<=", value: -8, availability: "automated" },
      { id: "c1d", label: "Entry Center Nearby", kind: "supporting", role: "Timing Trigger", metricKey: "metric_entry_center_distance", formulaKey: "custom_expression", operator: "<=", value: 5, availability: "manual" },
      { id: "c1e", label: "Event Pressure Limited", kind: "negative", role: "Risk Warning", metricKey: "metric_event_pressure_score", formulaKey: "custom_expression", operator: ">=", value: 60, availability: "automated" },
    ],
  },
  {
    id: "recipe-leader-pullback",
    lineageId: "recipe-leader-pullback",
    version: 1,
    name: "Leader Pullback",
    purpose: "Track healthy resets of sector leaders.",
    opportunityType: "Leader Pullback",
    timeHorizon: "1 to 2 weeks",
    intendedUseCase: "Position Building",
    notes: "Standard sector leader reset monitoring.",
    createdAt: now,
    reviewConfig: { cadenceDays: 10, reviewTriggers: ["days_since_last_review"] },
    alertConfig: { cooldownHours: 24, dedupeKey: "state_change", priorityOnAttention: "High", priorityOnRisk: "Medium" },
    conditions: [
      { id: "c4", label: "Relative Strength Positive", kind: "required", role: "Eligibility Filter", metricKey: "metric_60d_relative_return", formulaKey: "custom_expression", operator: ">=", value: 0, availability: "automated" },
      { id: "c5", label: "Near 50D", kind: "supporting", role: "Timing Trigger", metricKey: "metric_price_vs_50d_gap", formulaKey: "custom_expression", operator: "between", value: [-6, 2], availability: "automated" },
      { id: "c6", label: "20D Momentum Controlled", kind: "supporting", role: "Timing Trigger", metricKey: "metric_20d_momentum", formulaKey: "custom_expression", operator: "<=", value: 6, availability: "automated" },
      { id: "c6b", label: "Volume Not Exploding", kind: "supporting", role: "Risk Warning", metricKey: "metric_volume_burst_ratio", formulaKey: "custom_expression", operator: ">=", value: 2.2, availability: "automated" },
      { id: "c6c", label: "Entry Zone Not Far", kind: "supporting", role: "Timing Trigger", metricKey: "metric_entry_center_distance", formulaKey: "custom_expression", operator: "<=", value: 6, availability: "manual" },
    ],
  },
  {
    id: "recipe-reset-recovery",
    lineageId: "recipe-reset-recovery",
    version: 1,
    name: "Reset Recovery",
    purpose: "Track sharp reset setups that are trying to stabilize without a full thesis break.",
    opportunityType: "Recovery Setup",
    timeHorizon: "1 to 3 months",
    intendedUseCase: "Position Building",
    notes: "Look for damage, then demand early recovery evidence and avoid weak balance sheets.",
    createdAt: now,
    reviewConfig: { cadenceDays: 5, reviewTriggers: ["earnings_soon", "days_since_last_review"] },
    alertConfig: { cooldownHours: 24, dedupeKey: "state_change", priorityOnAttention: "High", priorityOnRisk: "High" },
    conditions: [
      { id: "c7", label: "Reset Damage", kind: "required", role: "Eligibility Filter", metricKey: "metric_drawdown_from_252d_high", formulaKey: "custom_expression", operator: "<=", value: -20, availability: "automated" },
      { id: "c8", label: "20D Shock", kind: "supporting", role: "Supporting Evidence", metricKey: "metric_20d_momentum", formulaKey: "custom_expression", operator: "<=", value: -10, availability: "automated" },
      { id: "c9", label: "Low Bounce", kind: "supporting", role: "Timing Trigger", metricKey: "metric_rebound_from_20d_low", formulaKey: "custom_expression", operator: ">=", value: 5, availability: "automated" },
      { id: "c10", label: "Volatility Cooling", kind: "supporting", role: "Timing Trigger", metricKey: "metric_volatility_cooling_rate", formulaKey: "custom_expression", operator: "<=", value: -10, availability: "automated" },
      { id: "c11", label: "Volume Return", kind: "supporting", role: "Timing Trigger", metricKey: "metric_volume_burst_ratio", formulaKey: "custom_expression", operator: ">=", value: 1.15, availability: "automated" },
    ],
  },
  {
    id: "recipe-thesis-risk-monitor",
    lineageId: "recipe-thesis-risk-monitor",
    version: 1,
    name: "Thesis Risk Monitor",
    purpose: "Monitor active theses for stale review, event proximity, entry drift, and manual risk flags.",
    opportunityType: "Risk Monitoring",
    timeHorizon: "1 to 2 weeks",
    intendedUseCase: "Thesis Protection",
    notes: "This set is not for entry. It exists to pull attention forward when the thesis needs review.",
    createdAt: now,
    reviewConfig: { cadenceDays: 3, reviewTriggers: ["days_since_last_review", "earnings_soon"] },
    alertConfig: { cooldownHours: 12, dedupeKey: "state_change", priorityOnAttention: "High", priorityOnRisk: "High" },
    conditions: [
      { id: "c12", label: "Stale Thesis Review", kind: "supporting", role: "Review Trigger", metricKey: "metric_review_staleness_ratio", formulaKey: "custom_expression", operator: ">=", value: 1, availability: "manual" },
      { id: "c13", label: "Earnings Too Close", kind: "negative", role: "Risk Warning", metricKey: "metric_event_pressure_score", formulaKey: "custom_expression", operator: ">=", value: 50, availability: "automated" },
      { id: "c14", label: "Outside Entry Plan", kind: "supporting", role: "Review Trigger", metricKey: "metric_entry_center_distance", formulaKey: "custom_expression", operator: ">=", value: 6, availability: "manual" },
      { id: "c15", label: "Manual Risk Flag", kind: "negative", role: "Risk Warning", metricKey: "metric_manual_risk_pressure", formulaKey: "custom_expression", operator: ">=", value: 25, availability: "manual" },
    ],
  },
];

const seedLogicSets: LogicSet[] = seedRecipes.map((recipe) => ({
  id: recipe.id,
  lineageId: recipe.lineageId ?? recipe.id,
  version: recipe.version,
  name: recipe.name,
  purpose: recipe.purpose,
  opportunityType: recipe.opportunityType,
  timeHorizon: recipe.timeHorizon,
  intendedUseCase: recipe.intendedUseCase,
  notes: recipe.notes,
  createdAt: recipe.createdAt,
  retiredAt: recipe.retiredAt,
  reviewConfig: recipe.reviewConfig,
  alertConfig: recipe.alertConfig,
  outcomeConfig: recipe.outcomeConfig,
}));

const seedLogicRules: LogicRule[] = seedRecipes.flatMap((recipe) =>
  recipe.conditions.map((condition) => ({
    id: condition.id,
    lineageId: condition.id,
    setId: recipe.id,
    setVersion: recipe.version,
    label: condition.label,
    kind: condition.kind,
    role: condition.role,
    metricKey: condition.metricKey,
    formulaKey: condition.formulaKey,
    operator: condition.operator,
    value: condition.value,
    unit: condition.unit,
    humanDescription: condition.humanDescription,
    notes: condition.notes,
    availability: condition.availability,
    createdAt: recipe.createdAt,
  })),
);

export const seedData: AppData = {
  stocks: [
    { id: "stock-nvda", symbol: "NVDA", name: "NVIDIA", thesis: "Core AI backbone, monitoring for healthy resets.", createdAt: now },
    { id: "stock-amd", symbol: "AMD", name: "Advanced Micro Devices", thesis: "Semi leader, value opportunity on deep pullback.", createdAt: now },
    { id: "stock-tsla", symbol: "TSLA", name: "Tesla", thesis: "EV leader, high volatility monitor.", createdAt: now },
    { id: "stock-msft", symbol: "MSFT", name: "Microsoft", thesis: "Software giant, safe haven pullback tracker.", createdAt: now },
    { id: "stock-aapl", symbol: "AAPL", name: "Apple", thesis: "Consumer tech anchor.", createdAt: now },
    { id: "stock-googl", symbol: "GOOGL", name: "Alphabet", thesis: "Search and AI integration play.", createdAt: now },
    { id: "stock-amzn", symbol: "AMZN", name: "Amazon", thesis: "E-commerce and AWS scaling.", createdAt: now },
    { id: "stock-meli", symbol: "MELI", name: "MercadoLibre", thesis: "LatAm growth story.", createdAt: now },
    { id: "stock-uber", symbol: "UBER", name: "Uber Technologies", thesis: "Mobility and delivery network effects.", createdAt: now },
    { id: "stock-coin", symbol: "COIN", name: "Coinbase", thesis: "Crypto proxy monitor.", createdAt: now },
    { id: "stock-snow", symbol: "SNOW", name: "Snowflake", thesis: "Enterprise data cloud growth.", createdAt: now },
    { id: "stock-pltr", symbol: "PLTR", name: "Palantir", thesis: "Enterprise AI adoption tracker.", createdAt: now },
    { id: "stock-meta", symbol: "META", name: "Meta Platforms", thesis: "Ad spend and AI efficiency monitor.", createdAt: now },
    { id: "stock-nflx", symbol: "NFLX", name: "Netflix", thesis: "Streaming dominance and profitability.", createdAt: now },
    { id: "stock-adbe", symbol: "ADBE", name: "Adobe", thesis: "Creative cloud and generative AI.", createdAt: now },
    { id: "stock-crm", symbol: "CRM", name: "Salesforce", thesis: "SaaS execution play.", createdAt: now },
    { id: "stock-intc", symbol: "INTC", name: "Intel", thesis: "Turnaround story monitor.", createdAt: now },
    { id: "stock-mu", symbol: "MU", name: "Micron", thesis: "Memory cycle tracker.", createdAt: now },
    { id: "stock-avgo", symbol: "AVGO", name: "Broadcom", thesis: "Networking and infrastructure leader.", createdAt: now },
    { id: "stock-pypl", symbol: "PYPL", name: "PayPal", thesis: "Fintech valuation recovery play.", createdAt: now },
  ],
  recipes: seedRecipes,
  customMetrics: starterCustomMetrics,
  logicRules: seedLogicRules,
  logicSets: seedLogicSets,
  eyes: [
    { id: "eye-amd", stockId: "stock-amd", recipeId: "recipe-bargain-sale", createdAt: daysAgo(21), thesisSnapshot: "Deep discount logic.", lastReviewedAt: daysAgo(8) },
    { id: "eye-meli", stockId: "stock-meli", recipeId: "recipe-bargain-sale", createdAt: daysAgo(28), thesisSnapshot: "Growth compounder reset.", lastReviewedAt: daysAgo(5) },
    { id: "eye-nvda", stockId: "stock-nvda", recipeId: "recipe-leader-pullback", createdAt: daysAgo(18), thesisSnapshot: "Leader reset logic.", lastReviewedAt: daysAgo(2) },
    { id: "eye-tsla", stockId: "stock-tsla", recipeId: "recipe-reset-recovery", createdAt: daysAgo(24), thesisSnapshot: "High volatility reset recovery.", lastReviewedAt: daysAgo(11) },
    { id: "eye-msft", stockId: "stock-msft", recipeId: "recipe-leader-pullback", createdAt: daysAgo(14), thesisSnapshot: "Quality safety pullback.", lastReviewedAt: daysAgo(16) },
    { id: "eye-aapl", stockId: "stock-aapl", recipeId: "recipe-leader-pullback", createdAt: daysAgo(16), thesisSnapshot: "Ecosystem play pullback.", lastReviewedAt: daysAgo(9) },
    { id: "eye-googl", stockId: "stock-googl", recipeId: "recipe-leader-pullback", createdAt: daysAgo(12), thesisSnapshot: "AI integration reset.", lastReviewedAt: daysAgo(6) },
    { id: "eye-amzn", stockId: "stock-amzn", recipeId: "recipe-leader-pullback", createdAt: daysAgo(20), thesisSnapshot: "Retail/AWS efficiency.", lastReviewedAt: daysAgo(7) },
    { id: "eye-coin", stockId: "stock-coin", recipeId: "recipe-reset-recovery", createdAt: daysAgo(30), thesisSnapshot: "Crypto reset recovery watch.", lastReviewedAt: daysAgo(13) },
    { id: "eye-snow", stockId: "stock-snow", recipeId: "recipe-bargain-sale", createdAt: daysAgo(22), thesisSnapshot: "Data cloud discount.", lastReviewedAt: daysAgo(18) },
    { id: "eye-pltr", stockId: "stock-pltr", recipeId: "recipe-leader-pullback", createdAt: daysAgo(10), thesisSnapshot: "Enterprise AI adoption.", lastReviewedAt: daysAgo(4) },
    { id: "eye-meta", stockId: "stock-meta", recipeId: "recipe-leader-pullback", createdAt: daysAgo(15), thesisSnapshot: "Ad spend logic.", lastReviewedAt: daysAgo(3) },
    { id: "eye-nflx", stockId: "stock-nflx", recipeId: "recipe-leader-pullback", createdAt: daysAgo(11), thesisSnapshot: "Streaming dominance.", lastReviewedAt: daysAgo(5) },
    { id: "eye-adbe", stockId: "stock-adbe", recipeId: "recipe-leader-pullback", createdAt: daysAgo(19), thesisSnapshot: "Creative cloud anchor.", lastReviewedAt: daysAgo(12) },
    { id: "eye-crm", stockId: "stock-crm", recipeId: "recipe-leader-pullback", createdAt: daysAgo(25), thesisSnapshot: "SaaS execution play.", lastReviewedAt: daysAgo(20) },
    { id: "eye-intc", stockId: "stock-intc", recipeId: "recipe-reset-recovery", createdAt: daysAgo(35), thesisSnapshot: "Foundry turnaround risk watch.", lastReviewedAt: daysAgo(15) },
    { id: "eye-mu", stockId: "stock-mu", recipeId: "recipe-leader-pullback", createdAt: daysAgo(9), thesisSnapshot: "Memory cycle play.", lastReviewedAt: daysAgo(2) },
    { id: "eye-avgo", stockId: "stock-avgo", recipeId: "recipe-leader-pullback", createdAt: daysAgo(13), thesisSnapshot: "Infrastructure giant reset.", lastReviewedAt: daysAgo(4) },
    { id: "eye-pypl", stockId: "stock-pypl", recipeId: "recipe-reset-recovery", createdAt: daysAgo(27), thesisSnapshot: "Fintech reset recovery watch.", lastReviewedAt: daysAgo(17) },
    { id: "eye-nvda-risk", stockId: "stock-nvda", recipeId: "recipe-thesis-risk-monitor", createdAt: daysAgo(8), thesisSnapshot: "AI backbone thesis maintenance.", lastReviewedAt: daysAgo(6) },
    { id: "eye-msft-risk", stockId: "stock-msft", recipeId: "recipe-thesis-risk-monitor", createdAt: daysAgo(8), thesisSnapshot: "Quality compounder thesis maintenance.", lastReviewedAt: daysAgo(19) },
  ],
  alerts: [
    { id: "alert-amd-1", eyeId: "eye-amd", recipeId: "recipe-bargain-sale", recipeVersion: 1, title: "Deep drawdown still holding support", stateChange: "Watch Closely → Opportunity Zone Forming", whyNow: "Drawdown remains deep while price stays near the planned zone.", supportingEvidence: ["252일 고점 대비 하락률 심화", "진입 구간 중심값 근접"], risks: ["실적 발표까지 9일"], dataQuality: "Fresh", priority: "High", createdAt: daysAgo(1, 6), reviewed: false, usefulness: "Useful" },
    { id: "alert-tsla-1", eyeId: "eye-tsla", recipeId: "recipe-reset-recovery", recipeVersion: 1, title: "Recovery bounce is active but unstable", stateChange: "Becoming Interesting → Watch Closely", whyNow: "Short-term rebound triggered, but volatility is still elevated.", supportingEvidence: ["20일 저점 대비 반등률 통과"], risks: ["변동폭 냉각률 부족"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(0, 14), reviewed: false },
    { id: "alert-msft-1", eyeId: "eye-msft-risk", recipeId: "recipe-thesis-risk-monitor", recipeVersion: 1, title: "Thesis review is stale", stateChange: "Watch Closely → Thesis Risk Rising", whyNow: "Last thesis review is older than the preferred cadence.", supportingEvidence: ["논리 검토 경과 비율 상승"], risks: ["수동 재검토 필요"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(0, 10), reviewed: false },
    { id: "alert-coin-1", eyeId: "eye-coin", recipeId: "recipe-reset-recovery", recipeVersion: 1, title: "Volatility remains too hot", stateChange: "Becoming Interesting → Thesis Risk Rising", whyNow: "Price damage is present, but compression has not stabilized.", supportingEvidence: ["252일 고점 대비 하락률 충분"], risks: ["변동폭 냉각 실패", "높은 변동"], dataQuality: "Fresh", priority: "High", createdAt: daysAgo(0, 4), reviewed: false },
    { id: "alert-pltr-1", eyeId: "eye-pltr", recipeId: "recipe-leader-pullback", recipeVersion: 1, title: "Leader pullback remains constructive", stateChange: "Watch Closely → Opportunity Zone Forming", whyNow: "Relative strength stayed positive while pullback remains controlled.", supportingEvidence: ["60일 상대수익률 스프레드 양수"], risks: ["거래량 급증 주의"], dataQuality: "Fresh", priority: "Low", createdAt: daysAgo(2, 7), reviewed: true, usefulness: "Useful" },
    { id: "alert-pypl-1", eyeId: "eye-pypl", recipeId: "recipe-reset-recovery", recipeVersion: 1, title: "Reset recovery is still early", stateChange: "Not Relevant → Becoming Interesting", whyNow: "Damage and discount are large enough to keep tracking, but confirmation is incomplete.", supportingEvidence: ["252일 하락률 심화", "밸류에이션 할인"], risks: ["수익성 압박", "거래량 미확인"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(3, 5), reviewed: false, snoozedUntil: daysAgo(-1) },
    { id: "alert-nvda-1", eyeId: "eye-nvda", recipeId: "recipe-leader-pullback", recipeVersion: 1, title: "Leader pullback is near support", stateChange: "Becoming Interesting → Watch Closely", whyNow: "Price held near the 50-day area while relative strength stayed positive.", supportingEvidence: ["현재가-50일선 괴리율 안정", "60일 상대수익률 스프레드 양수"], risks: ["과열 재개 가능성"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(1, 2), reviewed: false, usefulness: "Useful" },
    { id: "alert-aapl-1", eyeId: "eye-aapl", recipeId: "recipe-leader-pullback", recipeVersion: 1, title: "Pullback remains controlled", stateChange: "Watch Closely → Opportunity Zone Forming", whyNow: "The pullback stayed shallow and the planned entry zone remains nearby.", supportingEvidence: ["진입 구간 중심 이탈 절대값 양호", "20일 가격 모멘텀 진정"], risks: ["실적 이벤트 접근"], dataQuality: "Fresh", priority: "Low", createdAt: daysAgo(2, 5), reviewed: true, usefulness: "Useful" },
    { id: "alert-meta-1", eyeId: "eye-meta", recipeId: "recipe-leader-pullback", recipeVersion: 1, title: "Strength remains but crowding is rising", stateChange: "Watch Closely → Attention Needed", whyNow: "Relative strength and support held, but position crowding needs a fast review.", supportingEvidence: ["60일 상대수익률 스프레드 강함", "현재가-50일선 괴리율 안정"], risks: ["거래량 급증 배수 상승"], dataQuality: "Fresh", priority: "High", createdAt: daysAgo(0, 18), reviewed: false },
    { id: "alert-snow-1", eyeId: "eye-snow", recipeId: "recipe-bargain-sale", recipeVersion: 1, title: "Discount is real but confirmation is mixed", stateChange: "Not Relevant → Becoming Interesting", whyNow: "The drawdown and valuation discount are large enough, but stabilization is still partial.", supportingEvidence: ["252일 고점 대비 하락률 심화", "밸류에이션 할인"], risks: ["변동폭 냉각률 불충분"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(2, 10), reviewed: false },
    { id: "alert-intc-1", eyeId: "eye-intc", recipeId: "recipe-reset-recovery", recipeVersion: 1, title: "Turnaround watch is still fragile", stateChange: "Becoming Interesting → Thesis Risk Rising", whyNow: "Damage is deep enough, but structural turnaround risk still dominates.", supportingEvidence: ["252일 하락률 심화"], risks: ["구조적 전환 위험", "수동 위험 플래그 존재"], dataQuality: "Fresh", priority: "High", createdAt: daysAgo(0, 22), reviewed: false },
    { id: "alert-mu-1", eyeId: "eye-mu", recipeId: "recipe-leader-pullback", recipeVersion: 1, title: "Momentum leader is resetting cleanly", stateChange: "Watch Closely → Opportunity Zone Forming", whyNow: "Relative strength is still positive and the reset remains orderly.", supportingEvidence: ["60일 상대수익률 스프레드 강함", "현재가-50일선 괴리율 양호"], risks: ["메모리 사이클 뉴스 변동"], dataQuality: "Fresh", priority: "Medium", createdAt: daysAgo(1, 11), reviewed: false, usefulness: "Useful" },
  ],
  decisions: [
    { id: "decision-amd-1", eyeId: "eye-amd", alertId: "alert-amd-1", recipeId: "recipe-bargain-sale", recipeVersion: 1, stateAtDecision: "Opportunity Zone Forming", action: "Entered", note: "첫 분할 진입을 허용할 구간으로 판단했습니다.", concern: "실적 전 변동성 확대", thesisValid: "Yes", timing: "On Time", createdAt: daysAgo(1, 3) },
    { id: "decision-tsla-1", eyeId: "eye-tsla", alertId: "alert-tsla-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, stateAtDecision: "Watch Closely", action: "Skipped", note: "반등은 나왔지만 아직 변동성 압축이 부족합니다.", concern: "추가 하락 재개 가능성", thesisValid: "Partly", timing: "Early", createdAt: daysAgo(0, 12) },
    { id: "decision-msft-1", eyeId: "eye-msft-risk", alertId: "alert-msft-1", recipeId: "recipe-thesis-risk-monitor", recipeVersion: 1, stateAtDecision: "Thesis Risk Rising", action: "Revised", note: "논리 검토 일정을 당겼고 진입 계획을 다시 확인했습니다.", concern: "검토 공백 장기화", thesisValid: "Yes", timing: "Late", createdAt: daysAgo(0, 8) },
    { id: "decision-coin-1", eyeId: "eye-coin", alertId: "alert-coin-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, stateAtDecision: "Thesis Risk Rising", action: "Rejected", note: "변동성이 과도해 아직 복구 구간으로 보기 어렵습니다.", concern: "가격 안정화 부재", thesisValid: "No", timing: "On Time", createdAt: daysAgo(0, 3) },
    { id: "decision-pltr-1", eyeId: "eye-pltr", alertId: "alert-pltr-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, stateAtDecision: "Opportunity Zone Forming", action: "Entered", note: "상대강도가 유지돼 작은 추적 포지션을 열었습니다.", concern: "과열 재개 가능성", thesisValid: "Yes", timing: "On Time", createdAt: daysAgo(2, 3) },
    { id: "decision-pypl-1", eyeId: "eye-pypl", alertId: "alert-pypl-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, stateAtDecision: "Becoming Interesting", action: "Snoozed", note: "설정은 흥미롭지만 확인 신호 전까지 유예합니다.", concern: "거래량과 반등 질 부족", thesisValid: "Partly", timing: "Early", createdAt: daysAgo(3, 2) },
    { id: "decision-nvda-1", eyeId: "eye-nvda", alertId: "alert-nvda-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, stateAtDecision: "Watch Closely", action: "Revised", note: "지금은 추격보다 질 좋은 눌림 확인이 더 중요합니다.", concern: "단기 과열 재가속", thesisValid: "Yes", timing: "On Time", createdAt: daysAgo(1, 1) },
    { id: "decision-aapl-1", eyeId: "eye-aapl", alertId: "alert-aapl-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, stateAtDecision: "Opportunity Zone Forming", action: "Entered", note: "계획 구간과의 거리가 좁아 추적 진입을 허용했습니다.", concern: "실적 전후 방향성", thesisValid: "Yes", timing: "On Time", createdAt: daysAgo(2, 2) },
    { id: "decision-meta-1", eyeId: "eye-meta", alertId: "alert-meta-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, stateAtDecision: "Attention Needed", action: "Revised", note: "논리는 유지하지만 과열과 거래량 팽창을 같이 경계하도록 규칙을 조정했습니다.", concern: "군중 쏠림", thesisValid: "Partly", timing: "On Time", createdAt: daysAgo(0, 16) },
    { id: "decision-snow-1", eyeId: "eye-snow", alertId: "alert-snow-1", recipeId: "recipe-bargain-sale", recipeVersion: 1, stateAtDecision: "Becoming Interesting", action: "Skipped", note: "할인은 충분하지만 안정화 확인 전까지 추적만 유지합니다.", concern: "낙폭 이후 바닥 형성 미확인", thesisValid: "Partly", timing: "Early", createdAt: daysAgo(2, 8) },
    { id: "decision-intc-1", eyeId: "eye-intc", alertId: "alert-intc-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, stateAtDecision: "Thesis Risk Rising", action: "Rejected", note: "구조적 전환 불확실성이 커서 회복 세트 적용을 보류했습니다.", concern: "논리 자체가 약함", thesisValid: "No", timing: "On Time", createdAt: daysAgo(0, 20) },
    { id: "decision-mu-1", eyeId: "eye-mu", alertId: "alert-mu-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, stateAtDecision: "Opportunity Zone Forming", action: "Entered", note: "상대강도 유지와 깔끔한 리셋이 동시에 보여 추적 진입했습니다.", concern: "사이클 뉴스 변동성", thesisValid: "Yes", timing: "On Time", createdAt: daysAgo(1, 9) },
  ],
  outcomes: [
    { id: "outcome-amd-1", decisionId: "decision-amd-1", recipeId: "recipe-bargain-sale", recipeVersion: 1, reviewWindow: "2주", status: "Reviewed", priceChangeNote: "+6.2% 반등", maxRunupNote: "+9.8%", maxDrawdownNote: "-2.4%", lesson: "심한 낙폭과 지지 확인 조합이 유효했습니다.", recipeSuggestion: "실적 10일 이내 패널티를 조금 더 강하게 둘 수 있습니다.", createdAt: daysAgo(0, 2) },
    { id: "outcome-tsla-1", decisionId: "decision-tsla-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, reviewWindow: "1주", status: "Pending", priceChangeNote: "보합권", maxRunupNote: "+1.5%", maxDrawdownNote: "-4.8%", lesson: "반등만으로는 아직 부족했습니다.", recipeSuggestion: "냉각률 확인 전 진입 금지 규칙을 유지합니다.", createdAt: daysAgo(0, 1) },
    { id: "outcome-msft-1", decisionId: "decision-msft-1", recipeId: "recipe-thesis-risk-monitor", recipeVersion: 1, reviewWindow: "즉시", status: "Reviewed", priceChangeNote: "가격 변화보다 검토 품질 개선", maxRunupNote: "--", maxDrawdownNote: "--", lesson: "리스크 모니터 세트는 실제 가격보다 검토 누락 방지에 유효합니다.", recipeSuggestion: "검토 지연 신호를 홈에서 더 강하게 표시합니다.", createdAt: now },
    { id: "outcome-coin-1", decisionId: "decision-coin-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, reviewWindow: "5일", status: "Reviewed", priceChangeNote: "-7.4% 추가 하락", maxRunupNote: "+0.9%", maxDrawdownNote: "-8.6%", lesson: "고변동 구간 회피 판단이 유효했습니다.", recipeSuggestion: "변동폭 냉각 실패 시 위험 점수를 더 키울 수 있습니다.", createdAt: now },
    { id: "outcome-pltr-1", decisionId: "decision-pltr-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, reviewWindow: "10일", status: "Pending", priceChangeNote: "+3.1%", maxRunupNote: "+4.2%", maxDrawdownNote: "-1.8%", lesson: "상대강도 유지가 여전히 핵심입니다.", recipeSuggestion: "과열 캡 규칙을 더 미세하게 조정할 수 있습니다.", createdAt: daysAgo(1) },
    { id: "outcome-pypl-1", decisionId: "decision-pypl-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, reviewWindow: "1주", status: "Pending", priceChangeNote: "추가 확인 대기", maxRunupNote: "--", maxDrawdownNote: "--", lesson: "유예 결정은 아직 검증 중입니다.", recipeSuggestion: "거래량 복귀 전에는 타이밍 점수를 낮게 유지합니다.", createdAt: daysAgo(2) },
    { id: "outcome-nvda-1", decisionId: "decision-nvda-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, reviewWindow: "1주", status: "Pending", priceChangeNote: "+2.4%", maxRunupNote: "+3.8%", maxDrawdownNote: "-1.1%", lesson: "리더 종목은 진입보다 추적 품질이 먼저였습니다.", recipeSuggestion: "50일선 근접 시점의 경보 우선순위를 조금 높일 수 있습니다.", createdAt: daysAgo(0, 12) },
    { id: "outcome-aapl-1", decisionId: "decision-aapl-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, reviewWindow: "2주", status: "Reviewed", priceChangeNote: "+4.7% 반등", maxRunupNote: "+5.9%", maxDrawdownNote: "-1.3%", lesson: "얕은 눌림과 진입 구간 근접 조합이 잘 작동했습니다.", recipeSuggestion: "이벤트 압박이 낮을 때만 진입 허용하는 세부 규칙을 유지합니다.", createdAt: daysAgo(0, 7) },
    { id: "outcome-meta-1", decisionId: "decision-meta-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, reviewWindow: "즉시", status: "Pending", priceChangeNote: "과열 진정 여부 확인 중", maxRunupNote: "+1.8%", maxDrawdownNote: "-2.9%", lesson: "강한 종목일수록 거래량 팽창 경고를 분리해 보는 것이 유용했습니다.", recipeSuggestion: "거래량 급증 배수와 상대강도 조합을 별도 경고로 유지합니다.", createdAt: daysAgo(0, 9) },
    { id: "outcome-snow-1", decisionId: "decision-snow-1", recipeId: "recipe-bargain-sale", recipeVersion: 1, reviewWindow: "2주", status: "Pending", priceChangeNote: "-0.8%", maxRunupNote: "+2.2%", maxDrawdownNote: "-3.5%", lesson: "할인만으로는 부족하고 안정화 확인이 더 중요했습니다.", recipeSuggestion: "냉각률 조건 가중치를 조금 더 높입니다.", createdAt: daysAgo(1, 6) },
    { id: "outcome-intc-1", decisionId: "decision-intc-1", recipeId: "recipe-reset-recovery", recipeVersion: 1, reviewWindow: "1주", status: "Reviewed", priceChangeNote: "-4.1% 추가 하락", maxRunupNote: "+0.4%", maxDrawdownNote: "-5.2%", lesson: "구조적 위험이 크면 회복 시도 신호보다 논리 보호가 우선입니다.", recipeSuggestion: "수동 위험 압박 점수 임계치를 더 낮춰도 됩니다.", createdAt: daysAgo(0, 6) },
    { id: "outcome-mu-1", decisionId: "decision-mu-1", recipeId: "recipe-leader-pullback", recipeVersion: 1, reviewWindow: "8일", status: "Pending", priceChangeNote: "+2.9%", maxRunupNote: "+4.6%", maxDrawdownNote: "-1.7%", lesson: "상대강도 유지와 질 좋은 눌림의 조합이 여전히 핵심이었습니다.", recipeSuggestion: "리더 풀백 세트에서 거래량 조건은 보조 역할로 유지합니다.", createdAt: daysAgo(0, 11) },
  ],
  snapshots: [
    { stockId: "stock-amd", price: 142.35, drawdownPct: -32, nearSupport: true, stabilizationScore: 72, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-meli", price: 1648.2, drawdownPct: -27, nearSupport: true, stabilizationScore: 68, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-nvda", price: 1164.5, drawdownPct: -9, nearSupport: true, stabilizationScore: 75, relativeStrengthVsSpyPct: 4.2, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-tsla", price: 175.2, drawdownPct: -38, nearSupport: false, stabilizationScore: 42, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-msft", price: 420.5, drawdownPct: -7, nearSupport: true, stabilizationScore: 85, relativeStrengthVsSpyPct: 1.5, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-aapl", price: 190.2, drawdownPct: -11, nearSupport: true, stabilizationScore: 80, relativeStrengthVsSpyPct: 0.5, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-googl", price: 175.5, drawdownPct: -8, nearSupport: true, stabilizationScore: 78, relativeStrengthVsSpyPct: 2.1, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-amzn", price: 185.2, drawdownPct: -12, nearSupport: true, stabilizationScore: 82, relativeStrengthVsSpyPct: 3.5, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-coin", price: 210.5, drawdownPct: -42, nearSupport: false, stabilizationScore: 28, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-snow", price: 155.2, drawdownPct: -34, nearSupport: true, stabilizationScore: 52, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-pltr", price: 25.5, drawdownPct: -14, nearSupport: true, stabilizationScore: 72, relativeStrengthVsSpyPct: 8.5, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-meta", price: 485.2, drawdownPct: -10, nearSupport: true, stabilizationScore: 88, relativeStrengthVsSpyPct: 5.2, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-nflx", price: 620.5, drawdownPct: -6, nearSupport: true, stabilizationScore: 92, relativeStrengthVsSpyPct: 6.8, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-adbe", price: 475.2, drawdownPct: -18, nearSupport: true, stabilizationScore: 65, relativeStrengthVsSpyPct: -1.2, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-crm", price: 295.5, drawdownPct: -22, nearSupport: false, stabilizationScore: 48, relativeStrengthVsSpyPct: -4.5, valuationDiscount: true, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-intc", price: 30.2, drawdownPct: -45, nearSupport: true, stabilizationScore: 35, valuationDiscount: true, riskFlags: ["Structural turnaround"], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-mu", price: 125.5, drawdownPct: -15, nearSupport: true, stabilizationScore: 70, relativeStrengthVsSpyPct: 12.5, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-avgo", price: 1420.5, drawdownPct: -8, nearSupport: true, stabilizationScore: 86, relativeStrengthVsSpyPct: 4.8, valuationDiscount: false, riskFlags: [], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
    { stockId: "stock-pypl", price: 62.5, drawdownPct: -55, nearSupport: true, stabilizationScore: 42, valuationDiscount: true, riskFlags: ["Legacy growth pressure"], updatedAt: now, sourceName: "Market", freshness: "Fresh", isMock: true },
  ],
  rawBarArchives: [],
  universeSnapshots: [],
  processedFeatures: [],
  scanRuns: [],
  scanSignals: [],
  reviewLogs: [],
  forwardProofLedger: [],
  scannerSettings: {
    universeMode: "dynamic_current_universe",
    fallbackToFrozenUniverse: false,
    providerDelayMinutesAfterClose: 45,
    notifyNearMatches: true,
  },
};
