import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
test("create a real watchlist, reload it, and restore a validated file backup", async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const external: string[] = [];
  page.on("request", request => { if (!request.url().startsWith("http://127.0.0.1") && !request.url().startsWith("data:")) external.push(request.url()); });
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Add your first stock" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("first-run.png"), fullPage: true });
  await page.getByRole("button", { name: "Add your first stock" }).click();
  await page.getByRole("textbox", { name: "Ticker, e.g. AAPL" }).fill("AAPL");
  await page.getByRole("textbox", { name: "Company name", exact: true }).fill("Apple");
  await page.getByRole("textbox", { name: "Your thesis and what would change your mind" }).fill("Watch recurring revenue; review the next published results.");
  await page.getByRole("button", { name: "Save stock", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save stock", exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("button", { name: "Add your first stock" })).toHaveCount(0);
  await page.getByRole("tab", { name: "Watchlist", exact: true }).click();
  await expect(page.getByRole("button", { name: "Open AAPL Apple" })).toBeVisible();
  // Header actions must stay inside the viewport, including with Linux fonts.
  const settingsBounds = await page.getByRole("button", { name: "Settings", exact: true }).boundingBox();
  expect(settingsBounds).not.toBeNull();
  expect(settingsBounds!.x + settingsBounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByText("Your workspace", { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export complete backup" }).click();
  const download = await downloadPromise;
  const path = await download.path();
  const exported = JSON.parse(await readFile(path!, "utf8"));
  expect(exported.data.stocks).toHaveLength(1);
  expect(exported.data.stocks[0].symbol).toBe("AAPL");
  expect(exported.data.snapshots[0].isMock).toBe(false);
  const fileChooser = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Choose backup file" }).click();
  await (await fileChooser).setFiles(path!);
  await page.getByRole("button", { name: "Validate backup", exact: true }).click();
  await expect(page.getByText(/Backup validated/)).toBeVisible();
  const beforeRestore = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export current data and restore this backup" }).click();
  await beforeRestore;
  await expect(page.getByText("Backup restored.", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("workspace.png"), fullPage: true });
  expect(errors).toEqual([]);
  expect(external).toEqual([]);
});
test("sample data requires a deliberate action and all main sections render", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Explore sample workspace" }).click();
  await expect(page.getByText(/Sample data is present/)).toBeVisible();
  for (const name of ["Watchlist", "Recipes", "Journal", "Today"]) {
    await page.getByRole("tab", { name, exact: true }).click();
    await expect(page.getByRole("tab", { name, exact: true })).toHaveAttribute("aria-selected", "true");
  }
  await page.goBack();
  await expect(page.getByRole("tab", { name: "Journal", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.reload();
  await expect(page.getByRole("tab", { name: "Journal", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.screenshot({ path: testInfo.outputPath("sample-today.png"), fullPage: true });
});
test("keeps a damaged workspace available for export and restores its previous saved copy", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Explore sample workspace" }).click();
  await expect(page.getByText(/Sample data is present/)).toBeVisible();
  await page.evaluate(() => new Promise<void>((resolve, reject) => {
    const request = indexedDB.open("stockledger", 1);
    request.onsuccess = () => { const db = request.result; const tx = db.transaction("documents", "readwrite"); tx.objectStore("documents").put("damaged fixture", "stockledger.appData.v2"); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => reject(tx.error); };
  }));
  await page.reload();
  await expect(page.getByRole("button", { name: "Export recovery copy" })).toBeVisible();
  const recoveryPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export recovery copy" }).click();
  const recovery = JSON.parse(await readFile((await (await recoveryPromise).path())!, "utf8"));
  expect(recovery.current).toBe("damaged fixture");
  await page.getByRole("button", { name: "Restore previous saved copy" }).click();
  await expect(page.getByRole("button", { name: "Add your first stock" })).toBeVisible();
});
test("records a deliberate decision, reviews its outcome, and preserves an amendment", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Explore sample workspace" }).click();
  await page.getByRole("tab", { name: "Journal", exact: true }).click();
  await page.getByRole("button", { name: "New", exact: true }).click();
  await page.getByRole("button", { name: "Eye", exact: true }).click();
  await page.getByRole("button", { name: /AMD/ }).first().click();
  await page.getByRole("textbox", { name: "Why did you enter, skip, or revise?" }).fill("Regression review: wait for confirmed evidence.");
  await page.getByRole("button", { name: "Save Decision", exact: true }).click();
  await expect(page.getByText("Choose your thesis assessment.")).toBeVisible();
  await page.getByRole("button", { name: "Partly", exact: true }).click();
  await page.getByRole("button", { name: "Early", exact: true }).click();
  await page.getByRole("button", { name: "Save Decision", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "What did you learn?" })).toBeVisible();
  await page.getByRole("textbox", { name: "What did you learn?" }).fill("Verify coverage before drawing conclusions.");
  await page.getByRole("button", { name: "Save outcome review", exact: true }).click();
  await expect(page.getByText("Outcome review saved.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Edit", exact: true }).click();
  await page.getByRole("textbox", { name: "Why did you enter, skip, or revise?" }).fill("Regression amendment: reviewed the source.");
  await page.getByRole("button", { name: "Save Changes", exact: true }).click();
  await expect(page.getByText("Previous authored versions", { exact: true })).toBeVisible();
  await expect(page.getByText(/Regression review: wait for confirmed evidence/)).toBeVisible();
});
