import { Platform, StyleSheet } from "react-native";
const fontFamily = Platform.select({ ios: "System", android: "sans-serif", default: "system-ui" });
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f5f5f7",
  },
  loadingText: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "700",
    fontFamily,
  },
  routeNotice: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#f59e0b",
    backgroundColor: "#fffbeb",
  },
  routeNoticeTitle: {
    color: "#92400e",
    fontSize: 15,
    fontWeight: "800",
    fontFamily,
  },
  routeNoticeBody: {
    color: "#78350f",
    fontSize: 14,
    lineHeight: 20,
    fontFamily,
  },
  // Search Hero Styles
  homeStatsGrid: {
    flexDirection: "row",
    gap: 12,
  },
  // Stock Hero
  logicNavigatorCard: {
    marginBottom: 24,
    backgroundColor: "#f8fafc",
    padding: 18,
  },
  navigatorHeader: {
    marginBottom: 8,
  },
  navigatorEyebrow: {
    fontSize: 10,
    fontWeight: "900",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontStyle: "italic",
    marginBottom: 4,
  },
  navigatorBody: {
    fontSize: 14,
    color: "#475569",
    lineHeight: 20,
    fontWeight: "600",
  },
  twoColumnGrid: {
    flexDirection: "row",
    gap: 10,
  },
  logicRuleSelectCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  logicRuleSelectCardActive: {
    borderColor: "#0f172a",
    backgroundColor: "#eff6ff",
  },
  logicBuilderCompactCard: {
    padding: 12,
    borderRadius: 18,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 10,
  },
  logicRuleSelectTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    color: "#0f172a",
    fontFamily,
  },
  logicRuleSelectMeta: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    color: "#64748b",
    fontFamily,
  },
  logicRuleSelectToggle: {
    marginLeft: 10,
    alignSelf: "center",
    minHeight: 32,
    borderRadius: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
  },
  logicRuleSelectToggleActive: {
    borderColor: "#0f172a",
    backgroundColor: "#0f172a",
  },
  logicRuleSelectToggleText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#334155",
    fontFamily,
  },
  logicRuleSelectToggleTextActive: {
    color: "#ffffff",
  },
  homeSummaryStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailCallout: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#edf0f5",
  },
  detailCalloutLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontFamily,
  },
  detailCalloutBody: {
    marginTop: 4,
    color: "#111827",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily,
  },
  stockControlGroup: {
    gap: 6,
  },
  stockControlGroupLabel: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.35,
    fontFamily,
  },
  // Grid Layouts
  analysisGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  analysisGridItem: {
    width: "48.2%",
  },
  // Evidence Cards
  evidenceCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#eceef2",
    gap: 8,
    overflow: "hidden",
  },
  evidenceCardCompact: {
    padding: 10,
    gap: 7,
    minHeight: 166,
    borderColor: "#e5e7eb",
  },
  evidenceCardCompactDense: {
    padding: 9,
    gap: 6,
    minHeight: 154,
  },
  evidenceCardCompactPassed: {
    borderColor: "#bbf7d0",
  },
  evidenceCardCompactNear: {
    borderColor: "#fde68a",
  },
  evidenceCardCompactWarning: {
    borderColor: "#fcd34d",
  },
  evidenceCardCompactBlocked: {
    borderColor: "#fca5a5",
  },
  evidenceCardCompactStale: {
    borderColor: "#cbd5e1",
  },
  evidenceCardCompactPartial: {
    borderColor: "#d8b4fe",
  },
  evidenceCardCompactMock: {
    borderColor: "#bfdbfe",
  },
  evidenceCardCompactUnavailable: {
    borderColor: "#d1d5db",
  },
  evidenceCardInteractive: {
    shadowColor: "#111827",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  evidenceCardPressed: {
    transform: [{ scale: 0.985 }],
  },
  evidenceCompactAccent: {
    height: 3,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
    marginBottom: 2,
  },
  evidenceCompactHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  evidenceCardFamilyCompact: {
    color: "#6b7280",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.35,
    flexShrink: 1,
    fontFamily,
  },
  evidenceCardFamilyCompactDense: {
    fontSize: 8,
  },
  evidenceCardTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
    fontFamily,
  },
  evidenceCardTitleCompact: {
    fontSize: 13,
    fontWeight: "800",
    color: "#111827",
    lineHeight: 17,
  },
  evidenceCardTitleCompactDense: {
    fontSize: 12,
    lineHeight: 16,
  },
  evidenceCardHeaderMeta: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginLeft: 8,
  },
  evidencePinnedMark: {
    color: "#0f766e",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontFamily,
  },
  visualContainer: {
    height: 100,
    justifyContent: "center",
  },
  compactVisualContainer: {
    height: 58,
    justifyContent: "center",
  },
  compactEvidenceFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 4,
    gap: 8,
  },
  compactEvidenceValue: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
    flexShrink: 1,
    fontFamily,
  },
  compactEvidenceValueDense: {
    fontSize: 13,
  },
  compactEvidenceThreshold: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    fontFamily,
    flexShrink: 1,
    textAlign: "right",
    maxWidth: "52%",
  },
  compactEvidenceThresholdDense: {
    fontSize: 9,
    maxWidth: "54%",
  },
  compactEvidenceMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    marginTop: 3,
  },
  compactStatusBadge: {
    minHeight: 22,
    paddingHorizontal: 7,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  compactStatusBadgeDense: {
    minHeight: 20,
    paddingHorizontal: 6,
  },
  compactEvidenceStatusText: {
    color: "#111827",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
    fontFamily,
  },
  compactEvidenceStatusTextDense: {
    fontSize: 8,
  },
  compactEvidenceEffect: {
    color: "#4b5563",
    fontSize: 10,
    fontWeight: "700",
    fontFamily,
    flex: 1,
  },
  compactEvidenceEffectDense: {
    fontSize: 9,
  },
  compactFreshnessWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    maxWidth: "44%",
  },
  compactFreshnessText: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    fontFamily,
  },
  compactFreshnessTextDense: {
    fontSize: 9,
  },
  metricJumpChip: {
    paddingHorizontal: 11,
    minHeight: 44,
    borderRadius: 11,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    justifyContent: "center",
    overflow: "hidden",
  },
  metricJumpChipActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  metricJumpChipText: {
    color: "#4b5563",
    fontSize: 12,
    fontWeight: "700",
    fontFamily,
  },
  metricJumpChipTextActive: {
    color: "#ffffff",
  },
  detailMetricStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailMetricStripCompact: {
    gap: 6,
  },
  detailNarrativePanel: {
    marginTop: 12,
    padding: 15,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#eceef2",
    gap: 10,
  },
  detailNarrativePanelCompact: {
    marginTop: 10,
    padding: 12,
    gap: 8,
  },
  detailNarrativeHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  detailNarrativeHeaderCompact: {
    gap: 6,
  },
  detailNarrativeLead: {
    color: "#111827",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "700",
    fontFamily,
  },
  detailNarrativeSplit: {
    gap: 10,
  },
  detailNarrativeSplitCompact: {
    gap: 8,
  },
  detailNarrativeBlock: {
    gap: 4,
  },
  detailNarrativeLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    fontFamily,
  },
  detailHeroCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "#1e293b",
    gap: 14,
    overflow: "hidden",
  },
  detailHeroCardCompact: {
    padding: 12,
    borderRadius: 16,
    gap: 10,
  },
  detailHeroHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeroHeaderCompact: {
    gap: 10,
  },
  detailHeroEyebrow: {
    color: "#93c5fd",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontFamily,
  },
  detailHeroValue: {
    color: "#f8fafc",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    fontFamily,
  },
  detailHeroValueCompact: {
    fontSize: 21,
    lineHeight: 27,
  },
  detailHeroBadge: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "rgba(148, 163, 184, 0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeroBadgeText: {
    color: "#e2e8f0",
    fontSize: 11,
    fontWeight: "800",
    fontFamily,
  },
  detailHeroChart: {
    height: 296,
    borderRadius: 16,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1f2937",
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  detailHeroChartCompact: {
    height: 250,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 8,
  },
  detailHeroGrid: {
    ...StyleSheet.absoluteFill,
    justifyContent: "space-between",
    paddingVertical: 18,
  },
  detailHeroGridLine: {
    height: 1,
    backgroundColor: "rgba(148, 163, 184, 0.15)",
  },
  detailHeroThresholdLine: {
    position: "absolute",
    left: 12,
    right: 12,
    height: 1,
    backgroundColor: "rgba(248, 250, 252, 0.28)",
    borderStyle: "dashed",
  },
  detailHeroCurrentLine: {
    position: "absolute",
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: "#22c55e",
    opacity: 0.7,
  },
  detailHeroBarsRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 6,
    flex: 1,
  },
  detailHeroBarHit: {
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
    borderRadius: 10,
    paddingBottom: 4,
  },
  detailHeroBarHitActive: {
    backgroundColor: "rgba(148, 163, 184, 0.08)",
  },
  detailHeroBar: {
    width: "100%",
    borderRadius: 9,
    backgroundColor: "rgba(96, 165, 250, 0.48)",
    minHeight: 22,
  },
  detailHeroBarActive: {
    backgroundColor: "#60a5fa",
  },
  detailHeroLineOverlay: {
    ...StyleSheet.absoluteFill,
    pointerEvents: "none",
  },
  detailHeroLineDot: {
    position: "absolute",
    width: 8,
    height: 8,
    marginLeft: -4,
    marginBottom: -4,
    borderRadius: 4,
    backgroundColor: "#f8fafc",
  },
  detailHeroLineDotMuted: {
    position: "absolute",
    width: 7,
    height: 7,
    marginLeft: -3.5,
    marginBottom: -3.5,
    borderRadius: 3.5,
    backgroundColor: "#94a3b8",
    opacity: 0.9,
  },
  detailHeroLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  detailHeroLegendCompact: {
    gap: 6,
  },
  detailHeroLegendText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
    fontFamily,
    flexShrink: 1,
  },
  detailHeroFootnote: {
    color: "#94a3b8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    fontFamily,
  },
  detailSheetActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  detailSheetActionRowCompact: {
    gap: 6,
    marginTop: 8,
  },
  detailJumpSection: {
    marginTop: 10,
    gap: 8,
  },
  detailJumpSectionCompact: {
    marginTop: 8,
    gap: 6,
  },
  detailJumpTitle: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    fontFamily,
  },
  detailJumpRow: {
    gap: 8,
    paddingRight: 6,
  },
  detailDisclosurePanel: {
    marginTop: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#eceef2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  detailChecklistStack: {
    gap: 8,
  },
  detailChecklistRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  detailChecklistMarker: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  detailChecklistMarkerGood: {
    backgroundColor: "#22c55e",
  },
  detailChecklistMarkerWarning: {
    backgroundColor: "#f59e0b",
  },
  detailChecklistMarkerDanger: {
    backgroundColor: "#ef4444",
  },
  detailChecklistMarkerNeutral: {
    backgroundColor: "#94a3b8",
  },
  detailChecklistLabel: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "700",
    flexShrink: 1,
    fontFamily,
  },
  detailCountdownWrap: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
    minHeight: 140,
  },
  detailCountdownDays: {
    color: "#f8fafc",
    fontSize: 80,
    lineHeight: 86,
    fontWeight: "800",
    fontFamily,
  },
  detailCountdownUnit: {
    color: "#cbd5e1",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
    marginBottom: 14,
    fontFamily,
  },
  detailGaugeTrack: {
    height: 34,
    borderRadius: 18,
    overflow: "hidden",
    flexDirection: "row",
    position: "relative",
  },
  detailGaugeSafe: {
    flex: 1,
    backgroundColor: "#14532d",
  },
  detailGaugeWarn: {
    flex: 1,
    backgroundColor: "#92400e",
  },
  detailGaugeDanger: {
    flex: 1,
    backgroundColor: "#7f1d1d",
  },
  detailGaugeThreshold: {
    position: "absolute",
    top: -3,
    bottom: -3,
    width: 2,
    backgroundColor: "#f8fafc",
    opacity: 0.65,
  },
  detailGaugeCurrent: {
    position: "absolute",
    top: -5,
    bottom: -5,
    width: 4,
    borderRadius: 2,
    backgroundColor: "#60a5fa",
  },
  detailZoneTrack: {
    height: 52,
    borderRadius: 16,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1f2937",
    position: "relative",
    justifyContent: "center",
    overflow: "hidden",
  },
  detailZoneBand: {
    position: "absolute",
    top: 10,
    bottom: 10,
    borderRadius: 12,
    backgroundColor: "rgba(34, 197, 94, 0.32)",
    borderWidth: 1,
    borderColor: "rgba(74, 222, 128, 0.8)",
  },
  detailZoneMarker: {
    position: "absolute",
    top: 4,
    bottom: 4,
    width: 4,
    borderRadius: 2,
    backgroundColor: "#f8fafc",
  },
  freshnessDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#10b981", // Green
  },
  choiceRow: {
    gap: 10,
    paddingVertical: 4,
    paddingRight: 8,
  },
  operatorChip: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe5f0",
    alignItems: "center",
    justifyContent: "center",
  },
  operatorChipText: {
    color: "#0f172a",
    fontSize: 12,
    fontWeight: "800",
    fontFamily,
  },
  metricBuilderSectionCard: {
    padding: 12,
    borderRadius: 18,
    gap: 10,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#edf0f5",
  },
  metricBuilderSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  metricBuilderSectionTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
    fontFamily,
  },
  metricBuilderMetaGrid: {
    gap: 10,
  },
  metricBuilderMetaField: {
    gap: 4,
  },
  metricBuilderMiniLabel: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.35,
    fontFamily,
  },
  metricBuilderCompactRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  metricBuilderSelectorField: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  metricCalculatorAction: {
    minWidth: 82,
    marginLeft: 0,
  },
  formulaCanvas: {
    minHeight: 92,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe5f0",
    backgroundColor: "#ffffff",
    padding: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "flex-start",
  },
  formulaCanvasInvalid: {
    borderColor: "#dc2626",
    backgroundColor: "#fef2f2",
    shadowColor: "#dc2626",
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  formulaToken: {
    minHeight: 34,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  formulaTokenVariable: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  formulaTokenOperator: {
    backgroundColor: "#f8fafc",
    borderColor: "#dbe5f0",
  },
  formulaTokenNumber: {
    backgroundColor: "#fef3c7",
    borderColor: "#fcd34d",
  },
  formulaTokenText: {
    color: "#0f172a",
    fontSize: 12,
    fontWeight: "800",
    fontFamily,
  },
  metricBuilderStatusRow: {
    gap: 8,
  },
  metricBuilderStatusText: {
    fontSize: 11,
    fontWeight: "800",
    fontFamily,
  },
  metricBuilderStatusTextValid: {
    color: "#047857",
  },
  metricBuilderStatusTextInvalid: {
    color: "#b91c1c",
  },
  metricCalculatorGrid: {
    gap: 10,
  },
  metricCalculatorColumn: {
    gap: 8,
  },
  metricCalculatorPad: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  metricFunctionArgsCard: {
    gap: 8,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  metricFunctionArgBlock: {
    gap: 6,
  },
  selectChip: {
    width: "48%",
    minHeight: 70,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 4,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  selectChipActive: {
    borderColor: "#111827",
    backgroundColor: "#111827",
  },
  selectChipTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  selectChipTitleActive: {
    color: "#ffffff",
  },
  selectChipSubtitle: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
  },
  selectChipSubtitleActive: {
    color: "#d1d5db",
  },
  validationText: {
    color: "#ef4444",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
  previewDisclosure: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 12,
  },
  panelBadges: {
    alignItems: "flex-end",
    gap: 6,
  },
  formulaPanel: {
    marginTop: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#eceef2",
    gap: 12,
  },
  formulaTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  formulaBody: {
    color: "#4b5563",
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  formulaMeta: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
  },
  formulaToggleText: {
    color: "#111827",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  evidenceRelated: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  evidenceEffect: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
  },
  evidenceWhy: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "500",
  },
  evidenceRole: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    marginTop: 2,
  },
  evidenceSummary: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
  },
  evidenceMetricsRow: {
    flexDirection: "row",
    gap: 12,
  },
  alertTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 4,
    flexShrink: 1,
  },
  cardEyebrow: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontFamily,
  },
  cardTitle: {
    color: "#111827",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    fontFamily,
    flexShrink: 1,
  },
  cardBody: {
    color: "#4b5563",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily,
    flexShrink: 1,
  },
  dualColumn: {
    flexDirection: "row",
    gap: 12,
  },
  columnTitle: {
    color: "#111827",
    fontSize: 12,
    fontWeight: "700",
    fontFamily,
  },
  listLine: {
    color: "#4b5563",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    fontFamily,
  },
  stockGroupSummary: {
    color: "#4b5563",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
    marginTop: 6,
  },
  stockTriageHeader: {
    gap: 10,
  },
  stockTriageTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  stockTriageToggle: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontFamily,
  },
  stockTriageSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  stockTriagePrimaryMetric: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    fontFamily,
  },
  stockTriageSecondaryMetric: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    fontFamily,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
  },
  statusPassed: { backgroundColor: "rgba(16, 185, 129, 0.1)", borderColor: "#10b981" },
  statusNear: { backgroundColor: "rgba(56, 189, 248, 0.1)", borderColor: "#38bdf8" },
  statusWarning: { backgroundColor: "rgba(245, 158, 11, 0.1)", borderColor: "#f59e0b" },
  statusBlocked: { backgroundColor: "rgba(239, 68, 68, 0.1)", borderColor: "#ef4444" },
  statusPartial: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  statusUnavailable: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  statusStale: { backgroundColor: "#fef3c7", borderColor: "#f59e0b" },
  statusMock: { backgroundColor: "rgba(167, 139, 250, 0.1)", borderColor: "#a78bfa" },
  statusFailed: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  freshnessBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
  },
  freshnessFresh: { backgroundColor: "rgba(16, 185, 129, 0.1)", borderColor: "#10b981" },
  freshnessDelayed: { backgroundColor: "rgba(245, 158, 11, 0.1)", borderColor: "#f59e0b" },
  freshnessPartial: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  freshnessUnavailable: { backgroundColor: "#f3f4f6", borderColor: "#d1d5db" },
  freshnessStale: { backgroundColor: "#fef3c7", borderColor: "#f59e0b" },
  freshnessMock: { backgroundColor: "rgba(167, 139, 250, 0.1)", borderColor: "#a78bfa" },
  // Legacy/Required Compat
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#eceef2",
    shadowColor: "#111827",
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    overflow: "hidden",
  },
  pressableCardWrap: {
    borderRadius: 18,
  },
  pressableCardWrapPressed: {
    transform: [{ scale: 0.988 }],
    opacity: 0.96,
  },
  inputLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 8,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  analysisActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  dualDenseGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  compactMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
  },
  compactMetricText: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    fontFamily,
  },
  evidenceGroup: {
    gap: 10,
  },
  groupHeaderButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  groupHeaderToggle: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
    fontFamily,
  },
  evidenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  evidenceGridItem: {
    width: "48.5%",
  },
  evidenceColumn: {
    flex: 1,
    padding: 12,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#eceef2",
  },
  previewCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#eceef2",
  },
  previewLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily,
  },
  previewText: {
    marginTop: 6,
    color: "#111827",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily,
  },
  kindPill: {
    alignSelf: "flex-start",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily,
  },
  buttonPrimaryText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  inlineBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  flexOne: {
    flex: 1,
  },
  stack: {
    gap: 10,
  },
  thresholdWrap: {
    gap: 8,
  },
  thresholdTrack: {
    height: 6,
    backgroundColor: "#e5e7eb",
    borderRadius: 3,
    overflow: "hidden",
  },
  thresholdMarkerCurrent: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: "#111827",
  },
  thresholdMarkerThreshold: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: "#9ca3af",
  },
  entryZoneBand: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(16, 185, 129, 0.3)",
  },
  thresholdLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  thresholdLegendText: {
    color: "#64748b",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  freshnessVisual: {
    gap: 8,
  },
  freshnessTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#e5e7eb",
  },
  freshnessVisualText: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    fontFamily,
  },
  binaryVisual: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  binaryDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  binaryDotActive: {
    backgroundColor: "#111827",
  },
  binaryDotMuted: {
    backgroundColor: "#d1d5db",
  },
  binaryVisualText: {
    color: "#4b5563",
    fontSize: 12,
    fontWeight: "600",
    fontFamily,
  },
  miniTrendVisual: {
    height: 40,
  },
  miniTrendBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    height: 30,
  },
  miniTrendBar: {
    flex: 1,
    backgroundColor: "#d1d5db",
    borderRadius: 1,
  },
  miniTrendBarActive: {
    backgroundColor: "#111827",
  },
  riskGaugeTrack: {
    height: 6,
    flexDirection: "row",
    borderRadius: 3,
    overflow: "hidden",
  },
  riskGaugeSafe: {
    flex: 3,
    backgroundColor: "#10b981",
  },
  riskGaugeWarn: {
    flex: 1,
    backgroundColor: "#f59e0b",
  },
  riskGaugeDanger: {
    flex: 1,
    backgroundColor: "#ef4444",
  },
  checklistVisual: {
    gap: 6,
  },
  checklistItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  checklistDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  checklistDotGood: { backgroundColor: "#10b981" },
  checklistDotNeutral: { backgroundColor: "#9ca3af" },
  checklistDotWarning: { backgroundColor: "#f59e0b" },
  checklistDotDanger: { backgroundColor: "#ef4444" },
  checklistText: {
    color: "#4b5563",
    fontSize: 11,
    fontWeight: "700",
  },
  sparklineOverlay: {
    ...StyleSheet.absoluteFill,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 1,
    paddingHorizontal: 2,
    opacity: 0.4,
  },
  sparklineBar: {
    flex: 1,
    backgroundColor: "#d1d5db",
    borderRadius: 1,
  },
  sparklineBarActive: {
    backgroundColor: "#111827",
  },
  sparklineLine: {
    position: "absolute",
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: "#38bdf8",
  },
  sparklineLineMuted: {
    position: "absolute",
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: "#94a3b8",
  },
  eventCountdown: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  eventCountdownBadge: {
    minWidth: 52,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 14,
    alignItems: "center",
  },
  eventCountdownUrgent: {
    backgroundColor: "#fff7ed",
  },
  eventCountdownCalm: {
    backgroundColor: "#eff6ff",
  },
  eventCountdownValue: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    fontFamily,
  },
  eventCountdownLabel: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
    fontFamily,
  },
  eventCountdownMeta: {
    color: "#6b7280",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
    fontFamily,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 21,
    fontWeight: "800",
    lineHeight: 26,
    fontFamily,
  },
  sectionNote: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 17,
    fontFamily,
  },
  stepFlow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: "#e5e7eb",
    marginHorizontal: 6,
  },
  stepConnectorActive: {
    backgroundColor: "#111827",
  },
  stepNode: {
    width: 72,
    alignItems: "center",
    gap: 6,
  },
  stepDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  stepDotActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  stepDotComplete: {
    backgroundColor: "#e5e7eb",
    borderColor: "#e5e7eb",
  },
  stepDotText: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "800",
    fontFamily,
  },
  stepDotTextActive: {
    color: "#ffffff",
  },
  stepLabel: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
    fontFamily,
  },
  stepLabelActive: {
    color: "#111827",
  },
  conditionRequired: {
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#38bdf8",
  },
  conditionSupporting: {
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#10b981",
  },
  conditionNegative: {
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#f59e0b",
  },
  conditionDisqualifier: {
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  versionHistoryStack: {
    gap: 10,
  },
  versionHistoryCard: {
    gap: 10,
  },
  versionHistoryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  versionHistoryTitleWrap: {
    flex: 1,
    gap: 3,
  },
  versionHistoryTitle: {
    color: "#0f172a",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    fontFamily,
  },
  versionHistorySubtitle: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    fontFamily,
  },
  versionHistoryMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  versionHistoryBody: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
    fontFamily,
  },
  versionHistoryActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  versionHistoryActionButton: {
    flex: 1,
  },
  logicInfoCard: {
    gap: 10,
  },
  logicInfoBody: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "600",
    fontFamily,
  },
});
